### ISSUE TITLE
Inconsistent FD radius?

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#108]
Compare 

https://github.com/poldracklab/mriqc/blob/ab49505f4379be576e5ed923fb3fbe9186562b14/mriqc/interfaces/viz_utils.py#L313

with

https://github.com/poldracklab/mriqc/blob/ab49505f4379be576e5ed923fb3fbe9186562b14/mriqc/qc/functional.py#L179

**Comment by oesteban** [comment]
Yes, looks like an error. Thanks for spotting it.
