### ISSUE TITLE
[agave] Clean up debug outputs

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#110]
After **successfully** running mriqc (0.6.0) - I'm getting the following outputs (list truncated):
![capture](https://cloud.githubusercontent.com/assets/238759/15488168/8a9d2326-2108-11e6-9182-7c2153ecae62.PNG)

1. Could we move the debug files (.out, .err) to a debug folder so they would not clutter the output? Right now they are the first thing the user sees.
2. Could the files be renamed in a more meaningful way? To begin could .out be renamed to _out.txt? What do the multiple crn-automated-job-8002913717894451686-242ac113-0001-007.err files correspond to?

**Comment by oesteban** [comment]
This is partially fixed with the correction in archiving. I open an issue in the agave repo to discuss the hierarchy of resulting objects.
