### ISSUE TITLE
Anatomical summary spreadsheet has duplicate rows.

### ISSUE THREAD

**Issue by wtriplett** [poldracklab/mriqc#12]
Using commit 7e2ec2c.

Looks like there is an index column with no header also:

<img width="1044" alt="screen shot 2016-01-18 at 7 09 31 am" src="https://cloud.githubusercontent.com/assets/1926804/12406680/2491920e-be04-11e5-9334-f111c7ce0f20.png">

**Comment by wtriplett** [comment]
Oscar I'm happy to try to look into this. Feel free to assign it to me if you'd like!

**Comment by oesteban** [comment]
Great Thanks!

I guess you run the workflow twice with same options and without removing the file.

I don't know if I should say that this is kind of a feature, more than a bug. I could have deleted the csv file with every execution, but I have the feeling that it is interesting to have all the results always.

When generating the plots, however, the duplicates are dropped (and we only keep the last unique copies of the combination subject_id, session_id, scan_id and site_name).

But an option to remove the file would be enough

**Comment by wtriplett** [comment]
Oscar, thanks and sorry for the confusion on my end. When I double checked my paths, I wasn't actually using the commit I referenced but was using one I had installed from setup.py earlier today. If I use mriqcp.py from commit 7e2ec2c, then there is only one row as you said.

It seems like this is a non-issue and if you don't mind I'll close it.
