### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#137]
https://neurostars.org/p/4052/

**Comment by oesteban** [comment]
https://circleci.com/gh/oesteban/mriqc/66

**Comment by shoshber** [comment]
Unless I am misunderstanding something, the syntax error here doesn't have anything to do with rst2pdf. Python 3 doesn't accept the u prefix on string literals.

**Comment by oesteban** [comment]
Yes, you are right. I fixed that one among many other problems. After that, the tests don't pass because of rst2pdf. It does not mean that all the py3 problems are solved, but we are getting closer.

**Comment by oesteban** [comment]
Solved in #138
