### ISSUE TITLE
[ENH] Use pandoc instead rst2pdf since the latter does not support py3

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#139]
On the way to solve #137, after checking that https://github.com/rst2pdf/rst2pdf/issues/537 is apparently in a deadlock.

**Comment by oesteban** [comment]
We could try this: http://python-future.org/translation.html

**Comment by oesteban** [comment]
Close since I ported rst2pdf to python 3 (at least, the crucial needs of mriqc).

**Comment by jvarada** [comment]
What was your experience using the translation package to port rst2pdf? I was thinking of looking into porting dcmstack...

**Comment by oesteban** [comment]
Well, it is still in the middle. Tests are not passing and the project is quite abandoned. Hopefully it will change.

Porting dcmstack is a great effort, let me know if you need any help.
