### ISSUE TITLE
Revise documentation in PDF reports

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#14]
Some names of outputs have changed, and now the functional QC protocol includes together the spatial and the temporal metrics.

**Comment by oesteban** [comment]
Hi @craigmoodie, do you mind to add the table of image parameters we have included within the reports? Example: https://circle-artifacts.com/gh/poldracklab/mriqc/111/artifacts/0/home/ubuntu/outdir/multiple-subject-func/functional_group.pdf

**Comment by oesteban** [comment]
What do you think about removing the html documentation from the reports, and just provide a link to the online documentation (uploaded in readthedocs or something). We would link to the module that now contains all the QC measures (example here -> https://circle-artifacts.com/gh/poldracklab/mriqc/145/artifacts/0/home/ubuntu/outdir/doc/mriqc.qc.html).

The 'downside' is that I would need to move parts of the documentation we have in the html templates into those docstrings of the qc measures.

The upsides are that we release @craigmoodie of documenting this QC project, and I think he will really appreciate that, and that docs can be built automatically with each release.

**Comment by vsoch** [comment]
+1 on this idea - Sphinx is really great, and it's nice to have docs that live with the code.

**Comment by oesteban** [comment]
Ok, this issue will be split in #46, #45 and #47.
