### ISSUE TITLE
Review the implemented aMRI workflow

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#15]
Review the current workflow in detail and identify potential new features that are needed, weak points, possible new measures, etc.

**Comment by oesteban** [comment]
I don't know what @wtriplett would think of this, but I consider that there is an important problem in these workflows.

The first processing task is a resampling using the reorient tool of afni. If the reorientation only deals with axis order and direction, then no problem. But I suspect that it also corrects for the tilt of the head.

If so, I think that we should compute the measures (particularly noise) BEFORE the resampling. Since skull-stripping and segmentation may benefit from tilt correction, what we could do is to map the resulting mask and segmentation back to original space, and then compute the QC measures there.

Is noise and other measures very sensitive to this resampling?

**Comment by wtriplett** [comment]
@oesteban yes I agree 100% that the measures should be computed using the unaltered image data.

**Comment by oesteban** [comment]
Ok, just to report it, #30 is integrated and functional :)

Any other suggestion to modify the pipelines?
