### ISSUE TITLE
Normalized frame displacement

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#153]
Currently frame displacement is expressed in mm. This makes it hard to compare across different TRs. It would be beneficial if FD was also expressed as speed (mm/s). This could be a new metric (to keep backward compatibility) as well as a new axis label in the FD plot (on the right hand side).

**Comment by oesteban** [comment]
Implemented in https://github.com/nipy/nipype/pull/1604. When it is merged in nipype I will update mriqc.
Same stands for DVARS (https://github.com/nipy/nipype/pull/1606).

**Comment by oesteban** [comment]
Will close this with #170

**Comment by oesteban** [comment]
Closed in #172
