### ISSUE TITLE
Mean and StdDev nifti files from Nipype's TSNR calculation

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#154]
It would be useful to have the mean and std dev files produced by nipype's tsnr algorithm when computing the tsnr. Right now the compute_tsnr method only outputs the tsnr file.

**Comment by oesteban** [comment]
The TSNR interface of nipype would write those images. However, these outputs are not connected anywhere and thus, deleted. There are two options here. 1) Run nipype (http://nipype.readthedocs.io/en/latest/users/config_file.html) with the config option remove_unnecessary_outputs = false; or 2) Connect these outputs to a datasink, as we currently do with the TSNR.

I'd be very happy to see a PR for this :D

**Comment by jvarada** [comment]
@oesteban Could you take a look at this commit?

https://github.com/nih-fmrif/mriqc/commit/5eb1b44bc90ea6c1b71183352840a059dc474534

I added a datasink to save the outputs of the TSNR calc, but now the nifti files are being saved in both the folder created by the compute_tsnr node, and in the datasink node folder. Is this the correct behavior? Seems a bit wasteful to keep two copies of the files...

**Comment by oesteban** [comment]
Sorry, I missed this out. Could you send a PR? it looks good to me :)

**Comment by oesteban** [comment]
This is already in master.
