### ISSUE TITLE
Missing settings 

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#155]
There are no options to set the 'fd_radius' and 'correct_slice_timing' settings used in the functional workflow.

**Comment by jvarada** [comment]
Is there a way to set the start/stop indexes for the drop TRs node within the afni's hmc workflow in the settings?

**Comment by oesteban** [comment]
These are interesting questions. You are right. We should provide with a way to set all those parameters. A config json file?

**Comment by jvarada** [comment]
Merged in by #208
