### ISSUE TITLE
Installing from github repo

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#168]
I've been trying to install the latest version of master from github (in python 3), and I keep getting the following error:

```
mriqc varadajc$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    main()
  File "setup.py", line 40, in main
    version=__version__,
NameError: name '__version__' is not defined
```

I also tried installing via pip with the -e flag, and got the same error. 

I tested the setup.py file, and all the description variables from info.py appear in the locals() dictionary after they are compiled/executed in the scope, but for some reason python still says that the names are not defined. Any idea what could be going on?

**Comment by oesteban** [comment]
This is addressed in #138 . Hopefully I'll be merging it today. I'll let you know so that we confirm that it fixed the issue.

**Comment by oesteban** [comment]
#138 is now merged, please let me know if this is still an issue.

**Comment by jvarada** [comment]
This is fixed.
