### ISSUE TITLE
normalize fails to run

### ISSUE THREAD

**Issue by mgxd** [poldracklab/mriqc#185]
[Copy of a crashfile](http://pastebin.com/bzJuZD8G)

"Too many samples map outside moving image buffer. There are only 38344 valid points out of 1801501 total points."

I'm running into this error on about half of subjects in my dataset - any thoughts?

**Comment by oesteban** [comment]
Hi @mgxd this is a problem related to ANTs normalization. We are pretty aware of this problem, and for this reason, we have recently added a new normalization interface that will try new settings if the default ones fail.

Basically, the T1w image of your subject ```sub-voice968``` failed to be registered to the MNI template. This is particular of that case, so if you could share it with me, I could search for more appropriate settings. I will incorporate those settings into mriqc as a fallback.

For now, you can also try the following: use current master (this fallback thing was added last Friday) and give it a try. Maybe the quick and dirty settings I wrote work for you in this subject.

**Comment by oesteban** [comment]
Sorry, I see you are using the docker image.

Please confirm me if you could share that T1 image with me (or provide me with ANTs settings that work for you) and I will build a new mriqc image with those settings.

**Comment by mgxd** [comment]
@oesteban thanks for the reply - I have a T1 image I can share with you, just need your email.

**Comment by oesteban** [comment]
@mgxd I just copied you image, thanks for sharing. Sorry for my silence, I'm on it.

**Comment by oesteban** [comment]
Hi @mgxd, the PR just merged (see above) fixed the problem with this subject. It also requires to update niworkflows to the latest version (0.0.3a14).
