### ISSUE TITLE
Error creating derivatives folder

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#187]
This problem occurs when several mriqc processes try to create the out/derivatives folder at the same time (which is pretty common when running several tasks in parallel with launcher):

```
OSError: [Errno 17] File exists: 'out/derivatives'
    mkdir(name, mode)
```

The problem is that there are no practical locks that work across different python processes (and even harder, across compute nodes).

**Comment by rwblair** [comment]
In fmriprep we're doing a try catch around mkdir calls, and only ignoring exceptions with errno 17.

```
        try:
            if not op.exists(out_path):
                os.makedirs(out_path)
        except OSError as e:
            #  errno 17 is file exists, anything else may be catastrophic
            if e.errno != 17:
                # print error/try something else here.
```

**Comment by oesteban** [comment]
Yep. Actually, we should do:

```
from errno import EEXIST
```
And then
```
        try:
            if not op.exists(out_path):
                os.makedirs(out_path)
        except OSError as e:
            if e.errno != EEXIST:
                raise
```

In some systems, file exists may not be the error code 17 :)

**Comment by rwblair** [comment]
Nice. Should help keep us AmigaOS compatible:
https://github.com/kusma/amiga-dev/blob/master/targets/m68k-amigaos/posix/include/arpa/tftp.h#L51
