### ISSUE TITLE
Get to run the first anatomical QC workflow...

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#2]
... on the downsampled BIDS dataset.

**Comment by wtriplett** [comment]
Oscar please let me know if I can help with the anatomical workflow!

**Comment by oesteban** [comment]
Ok, great. It basically reproduces the workflow currently in QAP. I'm to post here the graph so we can discuss about it :)

**Comment by oesteban** [comment]
Hi @wtriplett, this is the current version of the aMRIQC workflow:

![amriqc](https://cloud.githubusercontent.com/assets/598470/12204357/1738ff70-b634-11e5-9479-90e781b1e7e8.png)

Let me know if you have any doubts :)

**Comment by oesteban** [comment]
https://circleci.com/gh/poldracklab/mriqc/11
