### ISSUE TITLE
Reorder csv column labels with subject/scan info left of measures

### ISSUE THREAD

**Issue by wtriplett** [poldracklab/mriqc#20]
So that they are grouped and separate from QC measurement values.

**Comment by oesteban** [comment]
I'm very sad you proposed this, but I understand (it's not a fun task, that's all). So I will do :)

**Comment by chrisfilo** [comment]
It's not that hard! Cehck this snippet:

https://github.com/INCF/openfmri2bids/blob/master/openfmri2bids/converter.py#L367

**Comment by oesteban** [comment]
Not hard at all, I know. But playing with pandas is always a bit boring :P.
