### ISSUE TITLE
Run inside docker as user

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#201]
What do you think about this, @chrisfilo (ref: https://denibertovic.com/posts/handling-permissions-with-docker-volumes/).

If an environment variable is passed through the `docker run` call, then this is executed:

```
#!/bin/bash

# Add local user
# Either use the LOCAL_USER_ID if passed in at runtime or
# fallback

USER_ID=${LOCAL_USER_ID:-9001}

echo "Starting with UID : $USER_ID"
useradd --shell /bin/bash -u $USER_ID -o -c "" -m user
export HOME=/home/user

exec /usr/local/bin/gosu user "$@"
```

Note 1: instead of defaulting a user id of 9001, if LOCAL_USER_ID is not defined I would let the docker container fall back to normal (i.e. root).

Note 2: sometimes CircleCI does not catch artifacts because of permissions. Probably, just mkdir'ing the output folders outside is enough to avoid that but I'm not sure. This would cover that case. Another use case (and this is more real, not very useful right now but who knows?): if docker scales up in TACC, this is exactly what we need to run these images.

**Comment by oesteban** [comment]
@jvarada: would this make it easier for you to run mriqc in the HPC?

**Comment by chrisfilo** [comment]
I guess this could be useful for Mac and Linux user running this locally.
If you decide to go with this solution make sure that lla of this user add
and gosu magic would be run only and only if the special variable
(LOCAL_USER_ID) is passed. Remember that after conversion singularity
containers are read only (so no useradd) and are running without elevated
privileges (so no gosu).

**Comment by jvarada** [comment]
@oesteban We are only allowed to run singularity containers in our HPC (no docker), so I don't really ever run mriqc inside docker other than for generating the singularity image out of it. As long as the scripts don't try to alter any of the permission in runtime within the container it should be fine for us.

**Comment by oesteban** [comment]
Doesn't seem like a burning need. Reopen when needed.

**Comment by chrisfilo** [comment]
BTW https://docs.docker.com/engine/reference/run/#user
