### ISSUE TITLE
participant vs. group refactoring - functional

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#205]
Currently `participant` level analysis is not generating any reports, because it's dependant on the group level (to produce distribution plots). This means that when data from a new subject arrives the user needs to run two commands to see the new report: `participant` and `group`. To make it easier to run MRIQC in a continuous mode (not once when all subjects are acquired, but on for each subject separately each time a new subject is acquired) I would propose the following:
- The `participant` level should generate participant reports.
- The distributions in participant reports should be replaced by a list of values for all QC metrics.
- The group level should be skipped if only one participant is selected.
- The group level report should include list of outlier participant/runs based on each of the metrics.

**Comment by oesteban** [comment]
Update after #219, for anatomical workflows only:

  - [x] The participant level should generate participant reports.
  - [x] The distributions in participant reports should be replaced by a list of values for all QC metrics.

**Comment by oesteban** [comment]
Created #225 so this issue is focused on the functional workflow only.
