### ISSUE TITLE
Discard first few columns when calculating y axis limits for FD and DVARS

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#211]
![2016-10-15 09_46_20-functional_sub-306 pdf - adobe acrobat reader dc](https://cloud.githubusercontent.com/assets/238759/19412082/acca08fc-92c2-11e6-8ce9-c1e003af7dcc.png)

**Comment by oesteban** [comment]
Isn't this done already? (just checking before I take on it)

**Comment by chrisfilo** [comment]
it was part of this PR (to your fork) https://github.com/oesteban/mriqc/pull/1

**Comment by oesteban** [comment]
Yeah, that is what I suspected. Can we close this one?

**Comment by chrisfilo** [comment]
yup
