### ISSUE TITLE
Calculation of SNR

### ISSUE THREAD

**Issue by nataliekoh** [poldracklab/mriqc#233]
Hi there. Based on my understanding, SNR is typically calculated as the mean signal intensity of the grey matter region divided by the standard deviation of the background/air region. In the structuralQA.py script, however, SNR is calculated as the mean of the foreground divided by the standard deviation of the same region. Can someone explain to me why this is? Thank you.

**Comment by oesteban** [comment]
Hi @nataliekoh,

There are many different opinions on how to compute the SNR of MRI scans. For example, please see [Dietrich et al. (2007)](http://dx.doi.org/10.1002/jmri.20969).

In the case of MRIQC, we have implemented several calculations of SNR. On one hand, we compute the snr as mean/sigma for each tissue (csf, wm, gm). On the other, we compute the snr as you suggest (again for the three main tissues) with the adjustments of Dietrich et al.

Let me know if you need any further explanation.
