### ISSUE TITLE
Rare possible race condition with xvfb-run causing issues launching mriqcp in parallel

### ISSUE THREAD

**Issue by wtriplett** [poldracklab/mriqc#25]
Started 290 of parallel QC runs on the same node, and the first 20 of them failed with the below error. It may have something to do with xvfb-run trying to determine a free display number by incremental search and causing a race condition. After some run time, the parallel jobs become unsynchronized and there have been no additional errors. 

Not sure this is a mriqcp-specific bug.

Traceback: 
Traceback (most recent call last):
  File "/home1/03872/wtriplet/software/mriqc/src/nipype/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/home1/03872/wtriplet/software/mriqc/src/nipype/nipype/pipeline/engine/nodes.py", line 404, in run
    self._run_interface()
  File "/home1/03872/wtriplet/software/mriqc/src/nipype/nipype/pipeline/engine/nodes.py", line 514, in _run_interface
    self._result = self._run_command(execute)
  File "/home1/03872/wtriplet/software/mriqc/src/nipype/nipype/pipeline/engine/nodes.py", line 640, in _run_command
    result = self._interface.run()
  File "/home1/03872/wtriplet/software/mriqc/src/nipype/nipype/interfaces/base.py", line 1046, in run
    runtime = self._run_wrapper(runtime)
  File "/home1/03872/wtriplet/software/mriqc/src/nipype/nipype/interfaces/base.py", line 1476, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home1/03872/wtriplet/software/mriqc/src/nipype/nipype/interfaces/base.py", line 1510, in _run_interface
    self.raise_exception(runtime)
  File "/home1/03872/wtriplet/software/mriqc/src/nipype/nipype/interfaces/base.py", line 1434, in raise_exception
    raise RuntimeError(message)
RuntimeError: Command:
3dSkullStrip -input /corral-repl/utexas/poldracklab/openfmri/inprocess/ds030_QAP/ds030-sub-10150.wrk/aMRIQC/SkullStripWorkflow/_data_sub-10150.session_1.anat_1...corral-repl..utexas..poldracklab..openfmri..inprocess..ds030_QAP..ds030-sub-10150..sub-10150..anat..sub-10150_T1w.nii.gz/skullstrip/sub-10150_T1w_resample.nii.gz -prefix sub-10150_T1w_resample_skullstrip.nii.gz
Standard output:
The intensity in the output dataset is a modified version
of the intensity in the input volume.
To obtain a masked version of the input with identical values inside
the brain, you can either use 3dSkullStrip's -orig_vol option
or run the following command:
  3dcalc -a /corral-repl/utexas/poldracklab/openfmri/inprocess/ds030_QAP/ds030-sub-10150.wrk/aMRIQC/SkullStripWorkflow/_data_sub-10150.session_1.anat_1...corral-repl..utexas..poldracklab..openfmri..inprocess..ds030_QAP..ds030-sub-10150..sub-10150..anat..sub-10150_T1w.nii.gz/skullstrip/sub-10150_T1w_resample.nii.gz -b ./sub-10150_T1w_resample_skullstrip.nii.gz+orig -expr 'a*step(b)' \
         -prefix ./sub-10150_T1w_resample_skullstrip.nii.gz_orig_vol
to generate a new masked version of the input.
Standard error:
/home1/03872/wtriplet/bin/xvfb-run: line 186: kill: (10002) - No such process
Return code: 1
Interface SkullStrip failed to run.

**Comment by wtriplett** [comment]
@oesteban I think the nipype afni preprocess interface for 3dSkullStrip has `_redirect_x = True` set explicitly (https://github.com/nipy/nipype/commit/280b582eebcc7cef15e407c4d19cfbd3390a3d3c). It may have been a requirement at some point, but it doesn't seem to be needed with the Jan 1 2016 compiled 3dSkullStrip (AFNI_16.0.00). 

If I remove the line in nipype/preprocess/afni that sets `_redirect_x = True` and re-run the workflow I have no issues running it in parallel on the same node.

**Comment by oesteban** [comment]
Thanks a lot @wtriplett . Could you open two issues in nipype about this?:

The first one would let the community know that our current approach to implement _redirect_x chokes when there are many parallel processes. I'm very aware that this is a pending task for us in nipype.

The second issue would point to the first one, and would basically say what you mention: is there a reason to have ```_redirect_x = True``` in that interface? And that as of AFNI 16 it's doesn't seem to need that flag?

For now, I will see if there's a way to modify that attribute and force mriqc to use it.

**Comment by oesteban** [comment]
I think this is fixed in the ```fix/xvfb-run``` branch. Since the fix doesn't work for afni versions <16, we keep it in this branch.

**Comment by oesteban** [comment]
Hey @wtriplett, have a look on https://github.com/nipy/nipype/pull/1328

**Comment by wtriplett** [comment]
@oesteban that's great and thanks for the helpful nypipe discussions!

**Comment by oesteban** [comment]
@wtriplett ok, the fix worked ok on lonestar5 :)

**Comment by wtriplett** [comment]
Excellent my plan is to run the dataset again tomorrow and try to test the SlurmGraph plugin. I'll let you know how it goes!

**Comment by chrisfilo** [comment]
+1 for using SlurmGraph!
