### ISSUE TITLE
Confounds plots over carpetplot have fixed units

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#256]
This happens since #241 was merged:

![fmriplot-error](https://cloud.githubusercontent.com/assets/598470/20034489/ae8f7abc-a37c-11e6-8f5b-90279cd4c2a0.png)

**Comment by chrisfilo** [comment]
Weird - that PR did not touch any of the code directly related to plot
limits. Are you sure #241 is to blame?

**Comment by oesteban** [comment]
I think some weird interaction with removing frames. I don't think #241 created a problem, it's more like it unveiled it.
