### ISSUE TITLE
T1w image previously skull-stripped

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#278]
https://poldracklab.github.io/mriqc/abide-reports/anatomical_sub-50818_ses-0_run-0_report.html

- [ ] Flag the file (show a warning)
- [x] CNR measure should not be computed on the air mask
- [x] SNR_D measures should not be computed.
- [x] FBER should not be computed

**Comment by RocaVincent** [comment]
So results will not be biased if we use MRIQC on previously skull-stripped T1 ?

**Comment by oesteban** [comment]
> So results will not be biased if we use MRIQC on previously skull-stripped T1 ?

Yes, they will. We are working on spotting these instances and making more consistent decisions.
