### ISSUE TITLE
Include scan parameters

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#29]
It would be useful to include the following scan parameters in the QC reports:

- [x] x/y/z dimension (in voxels)
- [x] scan length (in volumes, when applicable)
- [x] x/y/z resolution (in mm)
- [x] TR (when applicable; in seconds)

This is related to #23.

**Comment by oesteban** [comment]
From where should we gather these data?

**Comment by chrisfilo** [comment]
All of it can be read from nifti headers.

**Comment by oesteban** [comment]
Ok
