### ISSUE TITLE
Read BIDS trees

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#3]
Read the BIDS tree and get all functional and anatomical images.

**Comment by chrisfilo** [comment]
You might want to use some of this code I wrote for QAP some time ago:
https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/blob/master/scripts/qap_bids_data_sublist_generator.py

**Comment by oesteban** [comment]
Sure, that is my starting point ;)
