### ISSUE TITLE
Anatomical workflow: add N4ITK (from ANTs) for bias correction

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#30]
This derives from the conversation @craigmoodie and I had this morning.

**Comment by chrisfilo** [comment]
Could you elaborate a bit more. Bias field correction is a preprocessing step rather than quality measure. Do you want to plot the bias field in reports?

**Comment by oesteban** [comment]
Ok, you're right. A bit of explanation follows.

The origin of the problem. @craigmoodie has found problems computing the CNR (contrast-to-noise-ratio) in some scans of CNI (basically images with CNR=1.0). He thought (and after seeing his images, I think he is right) that the problem is the outcome of FSL FAST segmentations, which is not good at all.

If we computed, and corrected the images for bias, FAST would perform better (N4ITK is much better than the LS estimator that internally uses FAST, so we are already doing this correction). And, we could have better CNR estimations.

Additionally, bias may be very informative to assess the quality of images. We could report max, min and median values for the inhomogeneity inside the brainmask. Plotting it is one other option.

**Comment by chrisfilo** [comment]
Ok - I understand now. Seems like a nobrainer. BTW ANTs also includes a
segmentation algorithm called atropos which might be worth looking into:
https://vimeo.com/67814201.

**Comment by chrisfilo** [comment]
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3297199/

**Comment by oesteban** [comment]
yep, we also considered atropos. And one I made some time ago (MBIS http://www.sciencedirect.com/science/article/pii/S0169260714000996)

**Comment by craigmoodie** [comment]
Sorry for just chiming in now, somehow this email got buried under a bunch of other ones. I'm glad we're on the same page. Oscar, please let me know if you need help with the implementation.


Chris, I'm also going to test atropos to see how it performs versus FAST in the preprocessing pipeline.



Best,

Craig.


--

Craig Moodie

Postdoctoral Fellow

Poldrack Lab

Department of Psychology

Stanford University.




________________________________
