### ISSUE TITLE
Move Conform Interface to nipype

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#318]
https://github.com/poldracklab/mriqc/blob/0bf20da44005b7d354459a6b5f61002565717e92/mriqc/interfaces/common.py#L29

It could be reused in fmriprep.

**Comment by oesteban** [comment]
Yep, that was on my mind already. Before moving it into nipype, we should/could think of a possible improvement:

when changing the dtype from floating point to integer, we could/should make it to fit the range of the target integer type.

**Comment by oesteban** [comment]
something like

```
    data = im.get_data()
    if np.issubdtype(newdtype, np.integer) and not np.issubdtype(hdr.get_data_dtype(), np.integer):
        data -= data.min()
        data = (data / data.max()) * np.iinfo(newdtype).max
```

**Comment by chrisfilo** [comment]
Remind me why do we need to touch dtype?

**Comment by oesteban** [comment]
We don't in fmriprep. We do in mriqc, to conform images to the same data type.

**Comment by oesteban** [comment]
The dtype can be enabled with https://github.com/poldracklab/mriqc/blob/0bf20da44005b7d354459a6b5f61002565717e92/mriqc/interfaces/common.py#L21

**Comment by chrisfilo** [comment]
So all images are set to the same dtype? Which one?

**Comment by oesteban** [comment]
No, currently only T1s are changed dtype to uint16. They mostly arrive as int16 with only positive values.

**Comment by oesteban** [comment]
This is the corresponding PR to nipype: https://github.com/nipy/nipype/pull/1868

**Comment by oesteban** [comment]
Since I disabled the conform of the dtype, and the PR is there I think this issue can be closed.
