### ISSUE TITLE
Remove QAP dependencies

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#32]
This involves #31, and also the following tasks:

- Anatomical (http://preprocessed-connectomes-project.github.io/quality-assessment-protocol/#spatial-anatomical):

  - [x] Contrast-to-noise ratio (CNR), Foreground to Background Energy Ratio (FBER), Entropy Focus Criterion (EFC) and the artifacts (QI1) are python functions that can be encapsulated together with SNR in a nipype interface for quality metrics.
  - [x] Smoothnes of voxels (FWHM) uses ```3dFWHMx``` from afni, which currently misses a nipype interface.
  - [x] SNR is already in nipype, but probably will need a review.
  - [x] Summary measures: these are just counting voxels

- Functional spatial (http://preprocessed-connectomes-project.github.io/quality-assessment-protocol/#spatial-functional) adds the following to the anatomical list:

  - [x] Ghost to Signal Ratio (GSR) is a function using mainly numpy

- Functional temporal (http://preprocessed-connectomes-project.github.io/quality-assessment-protocol/#temporal-functional):

  - [x] Standardized DVARS involves several function calls, using numpy.
  - [x] Global correlation
  - [x] Outlier Detection uses ```3dToutcount``` command from AFNI which is not currently in nipype
  - [x] Median Distance Index uses ```3dTqual``` which is not in nipype
  - [x] Mean FD - Jenkinson: this is almost 100% moved to the mriqc.
  - [x] Number of volumes with FD greater than 0.2m, Percent of volumes with FD greater than 0.2mm: this is just numpy operations.

**Comment by chrisfilo** [comment]
This makes a lot of sense. This way a wider Nipype community could benefit from this work. Were you planning to move the pure python QC metrics to Nipype as well? We already have tSNR in there so it would make some sense.
