### ISSUE TITLE
.git/objects is huge (8GB)

### ISSUE THREAD

**Issue by yarikoptic** [poldracklab/mriqc#323]
Just did a fresh clone to find:
```shell
$> du -scm * .git/objects
1	CHANGES.txt
1	circle.yml
1	codecov.yml
1	docker
5	docs
1	LICENSE.txt
1	Makefile
1	MANIFEST.in
1	mriqc
20	notebooks
1	README.rst
1	requirements.txt
1	setup.py
1	version.py
8681	.git/objects
8705	total
```
I guess at some point docker image was committed/pushed to github?

**Comment by oesteban** [comment]
Hi @yarikoptic, 

You are right, I wanted to upload example reports of the ABIDE dataset to the gh-pages branch. We hit the 10GB maximum and took it down. However, I don't know how to clear up the git history.

If you know how to do it, I would really appreciate it :)

**Comment by yarikoptic** [comment]
if it is just a matter of 23932b87af32d520c38180f4f6863b52e8586695 (last in gh-pages) commit to be removed then something like this

```
git checkout gh-pages
git reset --hard 23932b87af32d520c38180f4f6863b52e8586695^
git push --force  origin gh-pages
# hopefully they do "gc" from time to time to remove stale bogus objects
# do local cleanup
git reflog expire --expire=now --all
git gc --prune=now
```

**Comment by yarikoptic** [comment]
btw -- doing it locally now to see if it would deliver the desired effect ;)

**Comment by yarikoptic** [comment]
yeap... had to go all the way back to creation of gh-pages branch just for the sake of it
```shell
10168  git reset --hard f65c0e0fb0959f67b7162d8389572099e06f46f6^
10172  git co master
10173  git remote rm origin      # since I can't force push and had to have those references gone
10174  git reflog expire --expire=now --all
10175  git gc --purge=now
```
alternative could be -- use git-annex for those files ...  at some point was looking to write a filter for filter-branch which would move desired files under git-annex control.  Similar thing was done by freesurfer developers (Z K) to convert monster CVS into manageable git/git-annex repository.

**Comment by oesteban** [comment]
Thanks very much, now:

```
$ du -hs .git
38M	.git
```
