### ISSUE TITLE
which ANTS are you using?

### ISSUE THREAD

**Issue by yarikoptic** [poldracklab/mriqc#324]
I see that it is not coming from neurodebian but manually installed:
```shell
root@7eee6c655377:/opt/ants# ls -lta | head
total 1289896
drwxr-xr-x 1 root root       14 Oct 12 02:51 ..
drwxr-xr-x 1 root root     5944 Oct 12 02:50 .
-rwxrwxr-x 1 1000 1000     2251 Jan 23  2015 ANTSAverage2DAffine.sh
-rwxrwxr-x 1 1000 1000     3899 Jan 23  2015 ANTSAverage3DAffine.sh
-rwxrwxr-x 1 1000 1000     4361 Jan 23  2015 ANTSpexec.sh
-rwxrwxr-x 1 1000 1000     5414 Jan 23  2015 ants.sh
```
and I don't remember how to make it report its version ;)

what was the reason to use manually installed one instead of the 2.1.0 from NeuroDebian?
(may be that is all in git history of the Dockerfile which was used to create the poldracklab/neuroimaging-core  but I am not sure which repo that is in...

**Comment by yarikoptic** [comment]
reply would be appreciated ;-) @poldrack @chrisfilo

**Comment by oesteban** [comment]
Sorry @yarikoptic, I am probably the one that should reply.

The early images of poldracklab/neuroimaging-core (dockerfiles in https://github.com/poldracklab/crn_base/tree/master/crn_base) were not based on neurodebian. Then we switched to neurodebian, but did not change the source for ANTs. We probably want to do that, so I'll write it down.

Answering to your question, the ANTs version is 2.1.0, available in the GitHub repo of ants (https://github.com/stnava/ANTs/releases/tag/v2.1.0). If I can recall correctly, the Debian jessie version.

**Comment by yarikoptic** [comment]
Thank you Oscar!
