### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#33]
- [x] Rename the main script from `mriqcp.py` to `mriqc`
- [ ] Update README.md

**Comment by oesteban** [comment]
I had to rename it from ```mriqc.py``` to ```mriqcp.py``` because it had conflicts with the module (I don't understand why). Is this possible? In that case, what about ```run_mriqc.py```?

**Comment by chrisfilo** [comment]
Maybe if you remove the .py the conflict will go away.

**Comment by oesteban** [comment]
Ok, that makes sense.

**Comment by oesteban** [comment]
This was it: https://github.com/poldracklab/mriqc/blob/98b94bebe40b8873f56490edbd3a1c24727ca5c6/setup.py#L27
