### ISSUE TITLE
Error: Too few arguments

### ISSUE THREAD

**Issue by parekhpravesh** [poldracklab/mriqc#338]
Greetings!

I just downloaded mriqc and got it to install. I already have FSL and AFNI installed and I did install ANTs (QAP pipeline runs fine). I am attempting to run a simple command:

`mriqc -i <path_to_BIDS_dataset> -o <path_to_some_output_directory> -w <path_to_some_input_directory>`

 
but it refuses to run with the following message:

> /home/JPJ/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
>   "This module will be removed in 0.20.", DeprecationWarning)
> usage: mriqc [-h] [-v]
>              [--participant_label [PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]]
>              [-d [{anat,anatomical,func,functional} [{anat,anatomical,func,functional} ...]]]
>              [-s SESSION_ID] [-r RUN_ID] [--nthreads NTHREADS]
>              [--n_procs N_PROCS] [--mem_gb MEM_GB] [--write-graph] [--dry-run]
>              [--use-plugin USE_PLUGIN] [--testing] [-w WORK_DIR]
>              [--report-dir REPORT_DIR] [--verbose-reports]
>              [--ants-nthreads ANTS_NTHREADS] [--ants-settings ANTS_SETTINGS]
>              [--hmc-afni] [--deoblique] [--despike] [--start-idx START_IDX]
>              [--stop-idx STOP_IDX] [--correct-slice-timing]
>              bids_dir output_dir {participant,group}
> mriqc: error: too few arguments

I have also tried

`mriqc -B ~/Data/bids_dataset -o out/ -w work/`

and

`mriqc -B ~/Data/bids_dataset -S S001 S002 -o out/ -w work/`

(replacing the paths properly) but get the exact same error. I have tried this with the example dataset which I obtained from the BIDS website and also some other test data.

Apologies if this is straight-up 101 and should be self-evident. Appreciate any help on the same.

Thanks and Regards
Pravesh

**Comment by chrisfilo** [comment]
Try:

`mriqc ~/Data/bids_dataset out/ participant --participant_label S001 -w work/`

**Comment by parekhpravesh** [comment]
Hello,

This works! The pipeline is running now! Thank you so much :D
