### ISSUE TITLE
Failure to find files in BIDS format

### ISSUE THREAD

**Issue by angoldst** [poldracklab/mriqc#347]
Hi All, 

really looking forward to enacting this on my lab's datasets. I'm in the PANLab at Stanford working with Leanne Williams. 

I have been trying to get the pip install version working and have been running into a number of issues. I have confirmed my files are in BIDS format using the validator, however when I run the mriqc call from the terminal no anatomical or functional files are found within the subject directories. 

Tracing back through the scripts, it appears that the collect_bids_data function (taken from the mriqc.utils.bids library) fails to correctly pull from the layout.get() output. Instead the function returns empty lists for both the func and t1w modalities.  

This also occurs when I run it on the downloadable example data sets as well. 

I've not yet been able to try the docker version, but hope to try that tomorrow when I'm back on campus. All of the data is housed on the SNI server, so hoping it will be easy to implement. 

Another minor issue that I ran into was with the BIDS validation website. The validator seems to fail when there are functional tasks with more than one run and also a req_label tag. 

Thanks so much. 
~Andrea
agoldpie@stanford.edu

**Comment by oesteban** [comment]
Hi @angoldst,

Regarding the BIDS validation bug, please report the details in their repository: https://github.com/INCF/bids-validator/issues. I'm sure they wil address your problem very quickly.

Regarding MRIQC: some very recent changes to the pybids library we rely upon broke the BIDS interpretation bit of mriqc. This problem should be fixed in #344. However the original bug has been reopened (#340), so I guess we still have problems.

I'll close this issue an follow up conversation in #340, if you don't mind.

**Comment by angoldst** [comment]
Thanks. Will keep a look out on #340.

Best,

~A
Andrea N. Goldstein-Piekarski, PhD
Postdoctoral Fellow

Williams PANlab
Stanford University School of Medicine
401 Quarry Rd Office 3C38
Stanford, CA 94305
(650) 497-6480

On Jan 30, 2017, at 9:53 AM, Oscar Esteban <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @angoldst<https://github.com/angoldst>,

Regarding the BIDS validation bug, please report the details in their repository: https://github.com/INCF/bids-validator/issues. I'm sure they wil address your problem very quickly.

Regarding MRIQC: some very recent changes to the pybids library we rely upon broke the BIDS interpretation bit of mriqc. This problem should be fixed in #344<https://github.com/poldracklab/mriqc/pull/344>. However the original bug has been reopened (#340<https://github.com/poldracklab/mriqc/issues/340>), so I guess we still have problems.

I'll close this issue an follow up conversation in #340<https://github.com/poldracklab/mriqc/issues/340>, if you don't mind.
