### ISSUE TITLE
Put mriqc on pypi

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#36]

**Comment by oesteban** [comment]
I suppose this is easy, but never did it. If you have bookmarked some link to point me to solve this fast, I'd really appreciate it :)

**Comment by oesteban** [comment]
Uploaded test package to testpypi repository: https://testpypi.python.org/pypi?name=mriqc&version=0.0.2rc1&:action=display

**Comment by oesteban** [comment]
```
sudo pip install -i https://testpypi.python.org/pypi mriqc
```
apparently works
