### ISSUE TITLE
Mosaics are showing too few slices and resampling images

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#360]
This regression was introduced in https://github.com/poldracklab/mriqc/pull/330

Before:
![image](https://cloud.githubusercontent.com/assets/238759/22567913/bb9fca80-e95f-11e6-8b10-8868bf2e495e.png)

After the PR was merged:
![image](https://cloud.githubusercontent.com/assets/238759/22567960/e5b2f3ec-e95f-11e6-9641-c73302878614.png)

**Comment by oesteban** [comment]
This is 50465 (see #273):
![newmosaic](https://cloud.githubusercontent.com/assets/598470/22572373/ad489d2e-e958-11e6-9f83-e6bfe0dfd6ba.png)

**Comment by chrisfilo** [comment]
It's still applying the affine from the header - that's why the head is rotated.
