### ISSUE TITLE
Hard code quality metrics calculated my mriqc in tests

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#37]
So far our tests are only smoke tests. It would be nice to see if calculate QC metrics do not change from commit to commit. This can be achieved by either hard coding output in tests or using CircleCI API to access artifacts from previous tests.

**Comment by oesteban** [comment]
What do you think of creating a bunch of tests for the anatomical using the brainweb?

About the functional, I don't know if there is something similar.

**Comment by chrisfilo** [comment]
I don't think brainweb can give us expected values of all our qc metrics
for simulated data so that would be a different test.

**Comment by oesteban** [comment]
Yes, we don't have expected values for all qc metrics, but we can test consistency across commits at least.

**Comment by chrisfilo** [comment]
So you mean running mriqc on multiple datasets simulated with the same
parameters and checking if the qc metrics are similar?

**Comment by oesteban** [comment]
Ok, I have added some theoretical tests. I'll be adding more of those.

What I'm to do specifically to close this issue:

- I will collect csv files, and compare the newly generated to the old ones. For now, I will only work with one old csv file, and a current one.
- I will perform one anova test for each measure repeated between builds. Also, show warnings when new fields disappear or appear.

This way we will keep track of (i) if the measures changed and which ones; and (ii) consistency of measures across time.

At some point I will reconsider how to deal with these 'snapshots' of the csv file.
