### ISSUE TITLE
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#371]
This error is seemingly affecting nipype and matplotlib (https://github.com/conda-forge/matplotlib-feedstock/issues/36, https://github.com/leelabcnbc/DevOps/pull/3/files).

**Comment by oesteban** [comment]
Solution:

```
conda install icu=56.1
```

**Comment by satra** [comment]
@oesteban - we should update the lxml package on conda-forge as well. this should really be installed automatically rather than separately.
