### ISSUE TITLE
External code review

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#38]
The code base could benefit from another set of eyes. We could ask @rwblair to look at the code base at  some point.

**Comment by oesteban** [comment]
That'd be awesome. Would you mind, @rwblair? Let's talk about this today at the meeting.

**Comment by oesteban** [comment]
I think this is ready for a review, @rwblair

**Comment by oesteban** [comment]
I don't think it makes much sense having this open as an issue for one year now... should we close and reopen if we have someone to do this? - @chrisfilo
