### ISSUE TITLE
Implement QC metrics upload

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#383]
- Whenever mriqc finishes analyzing _bold or _T1w file its metrics should be uploaded to a central location via a JSON HTTP PUT operation.
- This should be opt-out - users can disable it via a command line switch.
- Information about these metrics being shared should show in logs in the beginning and at the end of the run.
- Data submission should be disabled for development versions.

**Comment by oesteban** [comment]
This is finished with #464 right?
