### ISSUE TITLE
greedy participant selection

### ISSUE THREAD

**Issue by angoldst** [poldracklab/mriqc#385]
Hello again. Thank you all for your continued support in helping me get this going. Everything for the most part is working great. 

I just tried running an individual subject label "RAD1" for the functional QC and it looks like it performed the regular expression search for "RAD1*" rather than "RAD1$". I recognize that this issue is partially to blame due to the lack of leading zeros for subject codes, but wanted to flag just in case. 

Thanks again.

**Comment by chrisfilo** [comment]
@oesteban this seems related to https://github.com/INCF/pybids/issues/25 and should've been fixed with the new grabbit release...

**Comment by oesteban** [comment]
I can confirm this is currently happening
