### ISSUE TITLE
N4BiasField correction is being run twice

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#393]
Since it was moved inside the AFNI skullstrip workflow....

**Comment by rwblair** [comment]
So in fmriprep I could write a wrapper for the afni SS workflow that does bias correction if mriqc would prefer to do the bias correction explicitly.

**Comment by chrisfilo** [comment]
Maybe this could be handled, by a simple argument to the function creating
the workflow?

**Comment by oesteban** [comment]
Good catch, we probably are better off using the output from the AFNI skullstrip workflow, don't you think?

**Comment by chrisfilo** [comment]
What do you mean?

**Comment by oesteban** [comment]
Removing the second bias correction from MRIQC? instead of touching niworkflows?

**Comment by chrisfilo** [comment]
Ah yes  I see - indeed that would be better.

**Comment by rwblair** [comment]
Whoops. should of updated this thread before opening that PR.

**Comment by rwblair** [comment]
I'll close the niworkflows PR.
