### ISSUE TITLE
Silent test fails and a warning that should've been an error

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#395]
![image](https://cloud.githubusercontent.com/assets/238759/23377691/c8c4f7c8-fce5-11e6-9d3f-c928239dab2b.png)

Could be related to https://github.com/poldracklab/mriqc/issues/392

**Comment by oesteban** [comment]
This commit https://github.com/poldracklab/mriqc/commit/ba79f4a3ab1a6121a13c479ac3b190ed1da24431 fixed this.
