### ISSUE TITLE
Image size in anatomical report doesn't reflect true image size

### ISSUE THREAD

**Issue by wtriplett** [poldracklab/mriqc#40]
Spacing column look accurate.
Using `aa26618 HEAD@{0}: clone: from git@github.com:poldracklab/mriqc.git`

In report PDF file:
![screen shot 2016-02-23 at 12 04 42 pm](https://cloud.githubusercontent.com/assets/1926804/13265035/bacad0ea-da25-11e5-929c-d46d66f9970b.png)

In .nii file:
```
N-1 header file 'sub-2001/anat/sub-2001_T1w.nii.gz', num_fields = 43

all fields:
  name                offset  nvals  values
  ------------------- ------  -----  ------
  sizeof_hdr             0      1    348
  data_type              4     10
  db_name               14     18
  extents               32      1    0
  session_error         36      1    0
  regular               38      1    r
  dim_info              39      1    0
  dim                   40      8    3 320 320 208 1 1 1 1
  intent_p1             56      1    0.0
  intent_p2             60      1    0.0
  intent_p3             64      1    0.0
  intent_code           68      1    0
  datatype              70      1    4
  bitpix                72      1    16
  slice_start           74      1    0
  pixdim                76      8    -1.0 0.8 0.8 0.83 0.0 0.0 0.0 0.0
```

**Comment by wtriplett** [comment]
reports/utils.py:55
```{python}
newdf[['size_x', 'size_y', 'size_z']] = newdf[['size_x', 'size_y', 'size_z']].astype(np.uint8)
```

might need to use np.uint16 due to the larger sizes?

**Comment by oesteban** [comment]
absolutely, sorry for the issue.

**Comment by oesteban** [comment]
would you send a pr?

**Comment by wtriplett** [comment]
Sure! Sent.

Before:
![screen shot 2016-02-25 at 2 05 22 pm](https://cloud.githubusercontent.com/assets/1926804/13336045/db60e98a-dbc8-11e5-87ba-f427d4106d1c.png)


After:

![screen shot 2016-02-25 at 2 04 37 pm](https://cloud.githubusercontent.com/assets/1926804/13336023/bcadc36e-dbc8-11e5-92ae-a30242684b14.png)
