### ISSUE TITLE
Name tSNR in reports and documentation as tSNR rather than (structural SNR)

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#419]

**Comment by chrisfilo** [comment]
Isn't tSNR still labelled as SNR on BOLD group reports?

**Comment by oesteban** [comment]
Nope, there is an SNR (computed on the mean EPI) and a tSNR (computed on the tSNR map). And they are labeled as such.

**Comment by oesteban** [comment]
http://web.stanford.edu/group/poldracklab/mriqc/reports/func_group.html

SNR - after GSR
tSNR - after GCOR

**Comment by chrisfilo** [comment]
tSNR seems to be missing completely. I opened a separate issue #420
