### ISSUE TITLE
tSNR, AOR, AQI and other metrics missing from bold group reports

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#420]
This is latest passing master:
https://1628-49015296-gh.circle-artifacts.com/0/home/ubuntu/scratch/out/reports/bold_group.html

This is how it used to look:
http://web.stanford.edu/group/poldracklab/mriqc/reports/func_group.html

**Comment by oesteban** [comment]
It is very likely that `spikes_num` is missing or failing, and the reports are cut at that point.

**Comment by chrisfilo** [comment]
Isn't spike detector disabled by default since #398? Why would this influence if tSNR is plotted?

**Comment by oesteban** [comment]
This line https://github.com/poldracklab/mriqc/blob/master/mriqc/reports/group.py#L135 is error prone. Here we assume all the keys in `QCTYPE` have value. Since #398, `spike_num` may or may not be set in the json file, right?

This would be more tolerant with the IQMs accepting missing values (#377)

**Comment by chrisfilo** [comment]
I don't quite see how the line you quoted could lead to silently skipping a bunch of metrics in the group report...

tSNR is both in the individual report and the json file: https://1628-49015296-gh.circle-artifacts.com/0/home/ubuntu/scratch/out/reports/sub-ds003s01_task-rhymejudgment_bold.html https://1628-49015296-gh.circle-artifacts.com/0/home/ubuntu/scratch/out/derivatives/sub-ds003s01_task-rhymejudgment_bold.json

**Comment by oesteban** [comment]
Yes, in #398 we stopped writing `spikes_num` as a measure in the json file.

When building the group reports, the `QCTYPE` dictionary describes which IQMs can be plotted together in the same scatterplot and their units. There is an entry for `spikes_num` (https://github.com/poldracklab/mriqc/blob/master/mriqc/reports/group.py#L97).

Within the for loop, a new empty group corresponding to `spikes_num` is added [here](https://github.com/poldracklab/mriqc/blob/master/mriqc/reports/group.py#L146).

If you look at line 2036 of https://1628-49015296-gh.circle-artifacts.com/0/home/ubuntu/scratch/out/reports/bold_group.html, there is an empty csv table. When the javascript processes this csv table breaks and stops plotting all the remaining IQMs (even though they are present down below that point in the html).

**Comment by chrisfilo** [comment]
I see now
![image](https://cloud.githubusercontent.com/assets/238759/23806099/3dce890c-0575-11e7-804b-83a17f01f5d3.png)
