### ISSUE TITLE
Issue with ApplyTransforms

### ISSUE THREAD

**Issue by hermeckerogg** [poldracklab/mriqc#436]
Hi. Apologize but new to python and imaging in python.

I've been trying to test mriqc on my system, but I have three errors that seem to stem from the same workflow that end with:
ValueError: ApplyTransforms requires a value for input 'transforms'. For a list of required inputs, see ApplyTransforms.help()

I'm running Linux "Trusty" Ubuntu 14.04.5 LTS on a Windows 10 machine.

Nipype is currently not set up to call Matlab due to windows conflict but I was under the impression that this would not be an issue in mriqc

Not sure what is causing the issue.
Output of error files and pip freeze attached.

[crash-20170324-143933-Thomas-invert_xfm.a0-1d690dd0-f2b8-44ea-a249-21b6bbcd1b7f.txt](https://github.com/poldracklab/mriqc/files/869145/crash-20170324-143933-Thomas-invert_xfm.a0-1d690dd0-f2b8-44ea-a249-21b6bbcd1b7f.txt)

[crash-20170324-143933-Thomas-MNItpms2t1.a0-79abaa0e-04c1-428e-a40e-d197976b90f1.txt](https://github.com/poldracklab/mriqc/files/869147/crash-20170324-143933-Thomas-MNItpms2t1.a0-79abaa0e-04c1-428e-a40e-d197976b90f1.txt)

[crash-20170324-143934-Thomas-ResampleSegmentation.a0-f5bb6da9-d433-4323-aa5d-0805a063d86a.txt](https://github.com/poldracklab/mriqc/files/869150/crash-20170324-143934-Thomas-ResampleSegmentation.a0-f5bb6da9-d433-4323-aa5d-0805a063d86a.txt)

[pipFreezeoutput.txt](https://github.com/poldracklab/mriqc/files/869151/pipFreezeoutput.txt)

**Comment by chrisfilo** [comment]
Did you close this issue intentionally?

Have you tried running MRIQC [via Docker or Singularity](http://mriqc.readthedocs.io/en/latest/docker.html)?

**Comment by hermeckerogg** [comment]
No it just stopped being an issue after I'd tried a couple of different builds.

Stopped having problems with the calls to ANTs and ended up consistently getting issues with Traits (which is open).

**Comment by hermeckerogg** [comment]
No it just stopped being an issue after I'd tried a couple of different builds.

Stopped having problems with the calls to ANTs and ended up consistently getting issues with Traits (which is open).

Was not able to install Docker on my machine for some reason. 
Singularity however, I have not tried. I will give it a shot.
