### ISSUE TITLE
Use tissue segmentation instead of transforming MNI tissue maps

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#449]
This should speed things up since we will not require time-consuming nonlinear MNI registration.

**Comment by chrisfilo** [comment]
@oesteban we actually are doing this anyway right? This can be closed?

**Comment by oesteban** [comment]
The TPMs from MNI are only used to compute the overlap with FAST's ones. Please, feel free to reopen if this is not the idea.
