### ISSUE TITLE
Use affine MNI coregistration

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#450]
Should be enough for airmask in T1. Depends on #449.

**Comment by chrisfilo** [comment]
Another advantage of this would be that  the speed increase would allow use to use the same coregistration parameters in testing that we use in production.

**Comment by chrisfilo** [comment]
@oesteban this is done right?

**Comment by oesteban** [comment]
Not exactly: I use this simplified BSpline to get a slightly more precise registration.

I didn't close for that detail.

**Comment by oesteban** [comment]
(sorry, clicked the wrong button)

So, we need to decided if we keep this bspline (if we gain anything from it) or not

**Comment by chrisfilo** [comment]
Well the point is that the coregistration is much faster than it used to be and can be done on real size data on CircleCI.

**Comment by oesteban** [comment]
Ok, hold on. Revising everything this is indeed still open (see #471)
