### ISSUE TITLE
Test the classifier on CircleCI

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#451]
With a few positive and negative cases from ABIDE and ds000030. This will require speedups from #450 #449.

**Comment by oesteban** [comment]
Proposal:

1. We run the 0.9.4 on ABIDE and ds030, then add the T1w.csv to the repo. We should update the T1w.csv with each new release.

2. We run the training code on the ABIDE and run evaluation on ds030 as a test.

3. We can run the classifier on the 4 abide subjects we have and confirm the prediction.

This would be a bit different from what you proposed here, but I guess it covers sufficiently the need for testing the classifier. WDYT?
