### ISSUE TITLE
Readthedocs does not build part of the documentation

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#455]
Apparently 0.9.1 did build correctly

**Comment by chrisfilo** [comment]
Could you give me access? Username 'filo'

**Comment by oesteban** [comment]
Done

**Comment by chrisfilo** [comment]
The logs say builds are passing. What do you mean by "not building part of the documentation"?

**Comment by oesteban** [comment]
This: http://mriqc.readthedocs.io/en/stable/workflows.html should not be empty (see http://mriqc.readthedocs.io/en/0.9.1/workflows.html).
