### ISSUE TITLE
Installation issues: patching needed?

### ISSUE THREAD

**Issue by jooweg** [poldracklab/mriqc#470]
We had trouble getting the MRIQC toolbox to work at our cluster computers. We figured it out, and here is what we did. First of all, we could only get it to work with Python 3. Furthermore, it seems that some dependencies are missing when installing MRIQC via pip, and some packages need to be updated in order to make it work. Here's what we did to get the toolbox working in an anaconda environment:

module load anaconda3/4.3.0
conda create -n mriqc python=3 numpy pip
source activate mriqc
pip install setuptools
pip install --upgrade https://github.com/nipy/nipype/archive/master.zip
pip install duecredit
pip install --upgrade https://github.com/poldracklab/niworkflows/archive/master.zip

**Comment by oesteban** [comment]
Hi @jooweg, thanks for this information. Could you provide some information about your unsuccessful settings, so that we can:

1. Find out why stable settings didn't work
2. Write your experience in the documentation

Thanks!

**Comment by chrisfilo** [comment]
Hi @jooweg. Have you considered asking your admins to install Singularity (http://singularity.lbl.gov/)? It would make installing MRIQC, FMRIPREP, and other BIDS Apps with their corresponding dependencies trivial.

**Comment by jooweg** [comment]
Thanks for the replies! In the meantime, the problem has solved itself: setting up a new environment does work with the stable settings now, also using Python 2 (we replicated the initial problem and now it also works on all separate user accounts)! I guess a patch was issued for one of the libraries?

And thanks for the tip @chrisfilo, we're going to look into Singularity.

**Comment by oesteban** [comment]
Good to hear that. We definitely advice using containers to avoid installation issues.

BTW, please note that as of MRIQC 0.9.4, Python 2 is not supported anymore.

Feel free to reopen if there is something else for us to comment on or fix.
