### ISSUE TITLE
T1w intensity harmonization (or intensity normalization)

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#489]
I've been entertaining this idea for a while, and I think that it would make our measures a lot more homogeneous across sites.

These two refs. could give me a start:
- http://ceur-ws.org/Vol-347/p036.pdf
- http://ieeexplore.ieee.org/document/836373/

Other refs.:
- http://www.eyemaginary.com/Rendering/AutomaticHistogramWarping.pdf
- http://ieeexplore.ieee.org/document/537491/

**Comment by chrisfilo** [comment]
https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dUnifize.html

**Comment by chrisfilo** [comment]
These guys are doing 3dUnifize after N4BiasFieldCorrection - https://github.com/jlohmeier/atlasBREX.

**Comment by chrisfilo** [comment]
3dUnifize seems to be removing the bias field (see https://youtu.be/LxApX0Ijg5w) running it before N4 might impair the matrics that were suppose to measure bias field.

**Comment by oesteban** [comment]
I was referring to `3dSkullStrip` with the before/after. See implementation :)
