### ISSUE TITLE
[BUG] N4 not working for certain cases?

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#494]
On subject 51475 of ABIDE, we see this:
![cjv_outlier](https://cloud.githubusercontent.com/assets/598470/25813361/18f006ba-33ce-11e7-9bff-586d7da74369.png)

And the corresponding registration to MNI shows this bias:
![cjv_outlier-mosaics](https://cloud.githubusercontent.com/assets/598470/25813414/510ccd76-33ce-11e7-8624-447b89d8940b.png)

**Comment by chrisfilo** [comment]
The bias is much less apparent in skullstripping. I wonder why it failed.

**Comment by oesteban** [comment]
This is likely related to conforming (refs #318). I've checked and `N4BiasFieldCorrection` does not fail this dramatically if the input image is int32 instead of float32.
