### ISSUE TITLE
[something to look into] Update Docker to 1.10 to update manifest version to 2

### ISSUE THREAD

**Issue by vsoch** [poldracklab/mriqc#499]
hey @poldracklab! Here is a fun little docker hub api adventure, mostly for fun, but it will make integration with Singularity better for you down the line. I noticed recently that your image returns a version 1 of the Docker manifest, versus [version 2](https://docs.docker.com/registry/spec/manifest-v2-2/).  For example:

```
client=DockerApiConnection(image='poldracklab/mriqc')
DEBUG Headers found: Accept,Content-Type
VERBOSE Registry: index.docker.io
VERBOSE Namespace: poldracklab
VERBOSE Repo Name: mriqc
VERBOSE Repo Tag: latest
VERBOSE Version: None
VERBOSE Obtaining tags: https://index.docker.io/v2/poldracklab/mriqc/tags/list
DEBUG GET https://index.docker.io/v2/poldracklab/mriqc/tags/list
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?service=registry.docker.io&expires_in=9000&scope=repository:poldracklab/mriqc:pull
DEBUG Headers found: Accept,Authorization,Content-Type

manifest = client.get_manifest()
VERBOSE Obtaining manifest: https://index.docker.io/v2/poldracklab/mriqc/manifests/latest
DEBUG GET https://index.docker.io/v2/poldracklab/mriqc/manifests/latest
```
Yours has the old version 1 fields, which have `fsLayers` instead of `layers` like:

```
{'architecture': 'amd64',
 'fsLayers': [{'blobSum': 'sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4'},
...
```
and we can verify version 1 of the schema:

```
manifest['schemaVersion']
1
```
versus what version 2 looks like, [like this](https://docs.docker.com/registry/spec/manifest-v2-2/) and was added [here](https://github.com/moby/moby/commit/9f482a66ab37ec396ac61ed0c00d59122ac07453).

The reason this is important is because the newer schema returns information about the layer size. It should look something like this (this is for ubuntu):

```
In [3]: client.get_manifest()
VERBOSE Obtaining manifest: https://index.docker.io/v2/library/ubuntu/manifests/latest
DEBUG GET https://index.docker.io/v2/library/ubuntu/manifests/latest
Out[3]: 
{'config': {'digest': 'sha256:f7b3f317ec734a73deca91b34c2b1e3dd7454650da9c8ef3047d29a873865178',
  'mediaType': 'application/vnd.docker.container.image.v1+json',
  'size': 3624},
 'layers': [{'digest': 'sha256:aafe6b5e13de557451e1781fe7276620275625f970015cbd10036ab7d8ae27c0',
   'mediaType': 'application/vnd.docker.image.rootfs.diff.tar.gzip',
   'size': 46792902},
  {'digest': 'sha256:0a2b43a726608d3835aa027bbe181624789130c212eb191baa481f1d788a0676',
   'mediaType': 'application/vnd.docker.image.rootfs.diff.tar.gzip',
   'size': 815},
  {'digest': 'sha256:18bdd1e546d21240bd4c3e4e29032a38f18102d780a78686508d40fe01c60158',
   'mediaType': 'application/vnd.docker.image.rootfs.diff.tar.gzip',
   'size': 514},
  {'digest': 'sha256:8198342c3e05101bb56b0a585dc34e39346ece39ee5d39287cda24b1fb445fed',
   'mediaType': 'application/vnd.docker.image.rootfs.diff.tar.gzip',
   'size': 850},
  {'digest': 'sha256:f56970a44fd409805e3872cac236d29f5eed1a45e189bb765bcd2163c915f384',
   'mediaType': 'application/vnd.docker.image.rootfs.diff.tar.gzip',
   'size': 161}],
 'mediaType': 'application/vnd.docker.distribution.manifest.v2+json',
 'schemaVersion': 2}
```

I am trying to get a feature added to Singularity 2.3 so you can do:

```
singularity pull docker://poldracklab/mriqc
```

and it will both `create` and `import` docker layers into a `poldracklab-mriqc-latest.img` (or one that you name specifically):

```
singularity pull --name myprecious.img docker://poldracklab/mriqc
```

Given that you have the version 2 manifest, I can get the size automatically, and the container is generated without needing it. Given that I can't get this manifest, we can only return the default Singularity image size, or you would need to specify it:

```
singularity pull --size 4000 docker://poldracklab/mriqc
```

which is more annoying of the two use cases, as it would vary per image! We could also get the size of the compressed layers from the content header (while it's stream downloading to the system), but then this would only work given that you don't already have the layers cached. We also can't get the uncompressed size from the last 4 bytes in the file because this is 32 bit, so it [doesn't work](http://stackoverflow.com/questions/2712173/check-the-total-content-size-of-a-tar-gz-file) for files greater than 4GB. We could also just estimate with some other hack on the fly, but the higher powers above me (and I agree) would like this to come from a reliable (single) place and not rely on the user's python, tar, etc.

So my next logical question was - why is this image delivering a Manifest Schema 1?  I first checked out the [builds](https://hub.docker.com/r/poldracklab/mriqc/builds/) on Docker Hub, and they are over 6 months old! But duh, this is because you've been building and pushing from circle (makes sense, for testing right!) and those are [pushed during CI here](https://github.com/poldracklab/mriqc/blob/master/circle.yml#L69).

I then poked into the old manifest being served, and from the history, it looks like the v1Compatibility json (history) stops at April of this year:

```
for layer in manifest['history']: print(json.loads(layer['v1Compatibili
    ...: ty'])['created'])

2017-04-23T18:22:38.555180752Z
2017-04-23T18:22:28.997826306Z
2017-04-23T18:22:19.759039782Z
2017-04-23T18:22:10.947418041Z
2017-04-23T18:22:01.07861345Z
2017-04-23T18:21:54.31756029Z
2017-04-23T18:21:30.692066584Z
2017-04-23T18:21:24.244138728Z
2017-04-23T18:21:17.426181353Z
2017-04-23T18:20:44.055114417Z
2017-04-23T18:20:37.553078338Z
2017-04-23T18:19:39.267013266Z
2017-04-23T18:19:33.433588271Z
2017-04-23T18:19:21.2173366Z
2017-04-23T18:19:10.912841181Z
2017-04-23T18:16:10.119395228Z
2017-04-23T18:16:07.072211516Z
2017-04-23T18:15:52.52128285Z
2017-04-23T18:15:46.009745722Z
2017-04-23T18:15:36.445782669Z
2017-04-23T18:15:21.588705635Z
2017-04-23T18:15:18.094309164Z
2017-04-23T18:15:15.196973388Z
2017-04-23T18:15:11.113514794Z
2017-04-23T18:12:23.393168016Z
2017-04-23T18:12:20.789563151Z
2017-04-23T18:11:25.65503471Z
2017-04-23T18:10:49.379840044Z
2016-12-15T17:45:24.24960419Z
2016-12-15T17:45:23.840105252Z
2016-12-15T17:45:22.900373296Z
2016-12-15T17:45:22.024921767Z
2016-12-15T17:45:21.123443146Z
2016-12-15T17:45:19.987827436Z
```

That was largely just the wrong rabbit hole **jumps out**. My next thought was that it must be something to do with the build process - if the version of Docker on circle doesn't push a thing that can generate a version schema 2 manifest, then it would fall back to 1. You are installing [1.9.1](https://github.com/poldracklab/mriqc/blob/master/circle.yml#L3). And after digging a bit in the abysmal hole of blue sadness that is the Docker documentation base, I found [this tidbit](https://docs.docker.com/registry/compatibility/#registry-v23):

>> Manifest Push with Docker 1.9 and Older
>> The Docker Engine will construct a Schema 1 manifest which the registry will persist to disk.
>> When the manifest is pulled by digest or tag with any docker version, a Schema 1 manifest will be returned.

so **TLDR**: if you are able to update your Docker on Circle (1.10 or up), this would be really great, because images will be served from Docker Hub that can tell users (the Singularity client being one of them!) how fat they are (let's be honest, Poldracklab images are VERY fat) and then with a **TBD** pull command, it will just create the right image size, instead of failing and then trying to shove a really fat cat into a tiny box, which only results in kittastrophe.

**Comment by chrisfilo** [comment]
I think there reason why we are using version 1.9.1 is that this is the only one that supports caching on CircleCI right now. @oesteban if we pull last release like we do with fmriprep we can skip explicit caching and use more recent version of docker.

**Comment by vsoch** [comment]
ah makes sense. If/when you do an update, ping here and I can test to see if the manifest version is updated with the new build.

**Comment by oesteban** [comment]
@vsoch do you know how `docker save` should be used with docker 1.10? That's the only reason why we are hooked up to 1.9.

**Comment by vsoch** [comment]
Is it different? If you want to do like:

      docker save -o $HOME/docker/cache.tar ubuntu:xenial-20161213 ${DOCKER_IMAGE}:${DOCKER_TAG}

based on the [docs](https://docs.docker.com/engine/reference/commandline/save/#extended-description) I think it's pretty similar, the default will stream to tar, but with `-o/--output` you can specify a file without the `>`, like:

```
docker save -o fedora-latest.tar fedora:latest
```

Are you hitting a bug?

**Comment by oesteban** [comment]
We were force to use docker 1.9 because of CircleCI. Now with circle 2.0 this has been superseded :)

**Comment by vsoch** [comment]
woohoo!
