### ISSUE TITLE
[ENH] Integration tests for MRIQCWebAPI

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#508]
In CircleCI we should:

1. Clone https://github.com/poldracklab/mriqcwebapi (pin it to a particular commit or a tag)
2. Start the server in the background (before any of the MRIQC runs)
3. Add a parameter(s) to each mriqc run that (those parameters are not implemented yet, they will have to be added):
   1. Change the destination server URL to localhost (so the measurements would get pushed to the instance started in step 2)
   2. Make the client fail instead of just issuing a warning (see line https://github.com/poldracklab/mriqc/pull/464/files#diff-692376f1ba15a362ca9b41ca53a9ca82R179; in production we want just a warning on CircleCI we want a failure/exception)
4. Query the API to check if the expected measurements are there (this should happen after all MRIQC runs; here's a related code that is used so far to validate results without the API).

@oesteban warned my about potential issues with parallelization. At the moment we are running tests in two parallel containers. At some occasion the two containers can run on the same machine and when the api will be started (step 2) the two containers might compete for the same port. To avoid this situation we can use the CIRCLE_NODE_INDEX variables to pick a different port for each CircleCI container.

**Comment by 394822740** [comment]
> Add a parameter(s) to each mriqc run that (those parameters are not implemented yet, they will have to be added):

By "parameter" you mean the data field or something else?

**Comment by chrisfilo** [comment]
A command line argument.

**Comment by 394822740** [comment]
For instance, 

> curl -H "Content-Type: application/json" -X POST -d '{"modality": "bold","aor": "12312313", "aqi":"123123"}' http://0.0.0.0/bold

Would "modality": "bold" be a "parameter" ? 

If not, may I have an example?

**Comment by chrisfilo** [comment]
No. 

- Here is an explanation of what a command line argument is: https://en.wikipedia.org/wiki/Command-line_interface?oldformat=true#Arguments. 
- Here are existing MRIQC command line arguments http://mriqc.readthedocs.io/en/latest/running.html#command-line-interface. 
- Here is where command line arguments are defined in the MRIQC codebase: https://github.com/poldracklab/mriqc/blob/master/mriqc/bin/mriqc_run.py#L29. 
- Here is an example of a recent pull request adding a new feature that involved a new command line argument: https://github.com/poldracklab/mriqc/pull/501

**Comment by 394822740** [comment]
> Add a parameter(s) to each mriqc run that (those parameters are not implemented yet, they will have to be added):
> Change the destination server URL to localhost (so the measurements would get pushed to the instance started in step 2)
> Make the client fail instead of just issuing a warning (see line https://github.com/poldracklab/mriqc/pull/464/files#diff-692376f1ba15a362ca9b41ca53a9ca82R179; in production we want just a warning on CircleCI we want a failure/exception)


Do you have a preference where exactly should I add these two parameters, DESTINATION_URL and FAIL_CLIENT within this [doc](https://github.com/poldracklab/mriqc/blob/master/mriqc/bin/mriqc_run.py#L29.)?
For example, should it be under     # Workflow settings ,  # General performance or     # Control instruments?

**Comment by chrisfilo** [comment]
"Instrumental options" seems like the most natural fit.

**Comment by 394822740** [comment]
#under the group of parameters named,  Instrumental options
`  g_outputs.add_argument('--destination-URL', action='store', default='', type=str,
                           help='Change the destination server URL to localhost' )

    g_outputs.add_argument('--fail-client-option', action='store_true', default=False,
                           help='default is warning instead of failing the client' )`

As a starting point, does the way I add these two parameters look reasonable to you?

**Comment by chrisfilo** [comment]
This looks ok, but I would change the default for `--destination-URL` to `http://34.201.213.252:5000` and make the names and `help` strings more descriptive. For someone not deeply involved in implementing this feature the descriptions make little sense. Try to put yourself in the shoes of a user.

**Comment by 394822740** [comment]
Thanks! Will make the change accordingly. 
In addition, on line 175 - line 180, https://github.com/394822740/mriqc/blob/conrad/mriqc/reports/utils.py 
I made the change, aiming to make sure the service would point to the right end point (either http://0.0.0.0/bold or http://0.0.0.0/T1w), would this be overwritten if I change the `--destination-URL` to `http://34.201.213.252:5000` at the parameter setting? Just curious

**Comment by chrisfilo** [comment]
I'm not sure I fully understand. `http://0.0.0.0` is only "right" in context of testing. That is why we need a command line parameter to chose which URL will be used to reach the API. Does this answer your question?

**Comment by 394822740** [comment]
I see - understood.  http://34.201.213.252:5000  is this an AWS server we rented or what is it?

**Comment by chrisfilo** [comment]
Yes - the address will probably change before we launch, but we can update the default before releasing in a separate PR.

**Comment by 394822740** [comment]
When I try to run this
`docker run -it --rm -v /Users/Conrad/Desktop/circle-tests:/data:ro -v /Users/Conrad/Desktop/out:/out -v /Users/Conrad/labwork/mriqc:/usr/local/miniconda/lib/python3.6/site-packages/mriqc poldracklab/mriqc:latest /data /out participant --participant_label 50137 --upload-strict --mriqc-webapi=http://0.0.0.0/`

The error message below was shown 
`Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.9.4', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
ModuleNotFoundError: No module named 'mriqc.bin'
`
Ross and I haven't found an effective solution to it. 
May I have your advice? Thanks!

**Comment by chrisfilo** [comment]
What's the output of `ls -al /Users/Conrad/labwork/mriqc`?

**Comment by 394822740** [comment]
`
Conrads-MacBook-Pro:mriqc Conrad$ ls -al /Users/Conrad/labwork/mriqc
total 320
drwxr-xr-x  31 Conrad  staff   1054 May 23 18:14 .
drwxr-xr-x   5 Conrad  staff    170 May 19 23:15 ..
-rw-r--r--@  1 Conrad  staff   6148 May 19 23:16 .DS_Store
drwxr-xr-x   6 Conrad  staff    204 May 19 23:15 .circleci
-rw-r--r--   1 Conrad  staff    309 May 19 23:15 .dockerignore
drwxr-xr-x  13 Conrad  staff    442 May 23 18:19 .git
-rw-r--r--   1 Conrad  staff     31 May 19 23:15 .gitattributes
-rw-r--r--   1 Conrad  staff    721 May 19 23:15 .gitignore
-rw-r--r--   1 Conrad  staff    279 May 19 23:15 .pylintrc
-rw-r--r--   1 Conrad  staff    175 May 19 23:15 .readthedocs.yml
-rw-r--r--   1 Conrad  staff    204 May 19 23:15 .travis.yml
-rw-r--r--   1 Conrad  staff   8014 May 19 23:15 CHANGES.txt
-rw-r--r--   1 Conrad  staff   4598 May 19 23:15 Dockerfile
-rw-r--r--   1 Conrad  staff   1514 May 19 23:15 LICENSE.txt
-rw-r--r--   1 Conrad  staff    209 May 19 23:15 MANIFEST.in
-rw-r--r--   1 Conrad  staff   1644 May 19 23:15 Makefile
-rw-r--r--   1 Conrad  staff   4353 May 19 23:15 README.rst
drwxr-xr-x   3 Conrad  staff    102 May 23 18:14 __pycache__
-rw-r--r--   1 Conrad  staff   3309 May 19 23:15 circle.yml
-rw-r--r--   1 Conrad  staff    587 May 19 23:15 codecov.yml
drwxr-xr-x   3 Conrad  staff    102 May 19 23:15 docker
drwxr-xr-x   6 Conrad  staff    204 May 19 23:15 docs
drwxr-xr-x  17 Conrad  staff    578 May 23 18:14 mriqc
drwxr-xr-x   9 Conrad  staff    306 May 23 18:14 mriqc.egg-info
drwxr-xr-x   6 Conrad  staff    204 May 19 23:15 notebooks
-rw-r--r--   1 Conrad  staff    213 May 19 23:15 requirements.txt
-rw-r--r--   1 Conrad  staff    147 May 19 23:15 setup.cfg
-rw-r--r--   1 Conrad  staff   3161 May 19 23:15 setup.py
drwxr-xr-x   6 Conrad  staff    204 May 19 23:15 tests
-rwxr-xr-x   1 Conrad  staff    799 May 19 23:15 update-changes.sh
-rw-r--r--   1 Conrad  staff  68611 May 19 23:15 versioneer.py`

**Comment by chrisfilo** [comment]
Hmm this looks right. What about `ls -al /Users/Conrad/labwork/mriqc/mriqc/bin`?

**Comment by 394822740** [comment]
Conrads-MacBook-Pro:mriqc Conrad$ ls -al /Users/Conrad/labwork/mriqc/mriqc/bin
total 152
drwxr-xr-x  12 Conrad  staff    408 May 19 23:15 .
drwxr-xr-x  17 Conrad  staff    578 May 23 18:14 ..
-rw-r--r--   1 Conrad  staff    189 May 19 23:15 __init__.py
-rw-r--r--   1 Conrad  staff   4626 May 19 23:15 abide2bids.py
-rw-r--r--   1 Conrad  staff   2380 May 19 23:15 dfcheck.py
-rw-r--r--   1 Conrad  staff   8222 May 19 23:15 fs2gif.py
-rw-r--r--   1 Conrad  staff   4307 May 19 23:15 mriqc_clf.py
-rw-r--r--   1 Conrad  staff   4459 May 19 23:15 mriqc_fit.py
-rw-r--r--   1 Conrad  staff   2061 May 19 23:15 mriqc_plot.py
-rw-r--r--   1 Conrad  staff  15435 May 23 15:34 mriqc_run.py
-rw-r--r--   1 Conrad  staff   1071 May 19 23:15 nib_hash.py
-rw-r--r--   1 Conrad  staff   4902 May 19 23:15 subject_wrangler.py

**Comment by chrisfilo** [comment]
What about 
`docker run -ti --rm -v /Users/Conrad/labwork/mriqc:/usr/local/miniconda/lib/python3.6/site-packages/mriqc  --entrypoint=ls poldracklab/mriqc:latest -al /usr/local/miniconda/lib/python3.6/site-packages/mriqc`

**Comment by 394822740** [comment]
$ docker run -ti --rm -v /Users/Conrad/labwork/mriqc:/usr/local/miniconda/lib/python3.6/site-packages/mriqc --entrypoint=ls poldracklab/mriqc:latest -al /usr/local/miniconda/lib/python3.6/site-packages/mriqc
total 164
drwxr-xr-x 31 root root  1054 May 24 01:14 .
drwxr-xr-x  1 root root  4096 May 18 03:53 ..
-rw-r--r--  1 root root  6148 May 20 06:16 .DS_Store
drwxr-xr-x  6 root root   204 May 20 06:15 .circleci
-rw-r--r--  1 root root   309 May 20 06:15 .dockerignore
drwxr-xr-x 13 root root   442 May 24 01:19 .git
-rw-r--r--  1 root root    31 May 20 06:15 .gitattributes
-rw-r--r--  1 root root   721 May 20 06:15 .gitignore
-rw-r--r--  1 root root   279 May 20 06:15 .pylintrc
-rw-r--r--  1 root root   175 May 20 06:15 .readthedocs.yml
-rw-r--r--  1 root root   204 May 20 06:15 .travis.yml
-rw-r--r--  1 root root  8014 May 20 06:15 CHANGES.txt
-rw-r--r--  1 root root  4598 May 20 06:15 Dockerfile
-rw-r--r--  1 root root  1514 May 20 06:15 LICENSE.txt
-rw-r--r--  1 root root   209 May 20 06:15 MANIFEST.in
-rw-r--r--  1 root root  1644 May 20 06:15 Makefile
-rw-r--r--  1 root root  4353 May 20 06:15 README.rst
drwxr-xr-x  3 root root   102 May 24 01:14 __pycache__
-rw-r--r--  1 root root  3309 May 20 06:15 circle.yml
-rw-r--r--  1 root root   587 May 20 06:15 codecov.yml
drwxr-xr-x  3 root root   102 May 20 06:15 docker
drwxr-xr-x  6 root root   204 May 20 06:15 docs
drwxr-xr-x 17 root root   578 May 24 01:14 mriqc
drwxr-xr-x  9 root root   306 May 24 01:14 mriqc.egg-info
drwxr-xr-x  6 root root   204 May 20 06:15 notebooks
-rw-r--r--  1 root root   213 May 20 06:15 requirements.txt
-rw-r--r--  1 root root   147 May 20 06:15 setup.cfg
-rw-r--r--  1 root root  3161 May 20 06:15 setup.py
drwxr-xr-x  6 root root   204 May 20 06:15 tests
-rwxr-xr-x  1 root root   799 May 20 06:15 update-changes.sh
-rw-r--r--  1 root root 68611 May 20 06:15 versioneer.py

**Comment by chrisfilo** [comment]
I run out of ideas. Come in tomorrow and we can have a look.

**Comment by 394822740** [comment]
I can be there early in the morning if that works?  like 9 a.m ish?

**Comment by 394822740** [comment]
When would you be there?

**Comment by chrisfilo** [comment]
Lets hash details on slack

**Comment by 394822740** [comment]
sure

**Comment by oesteban** [comment]
Created tag to pin the new tests: https://github.com/poldracklab/mriqcwebapi/releases/tag/0.1.0
