### ISSUE TITLE
No module named base

### ISSUE THREAD

**Issue by jnecus** [poldracklab/mriqc#518]
Hello,

I have tried installing mriqc using the following command `pip install mriqc` in both a python 2.7 and python 3.0 anaconda environment. However, I am unable to run mriqc from the command line. I get the following error after typing` mriqc` on the command line

```
 File "/home/campus.ncl.ac.uk/b5013167/anaconda2/lib/python2.7/site-packages/mriqc-0.9.4+93.g0527851-py2.7.egg/mriqc/interfaces/anatomical.py", line 24, in <module>
    from niworkflows.interfaces.base import SimpleInterface
ImportError: No module named base

```

I have tried upgrading nipype to the latest version but still get this error.

Thanks,
Joe

**Comment by chrisfilo** [comment]
Using containers (either Docker and Singularity) is the recommended method of running mriqc. It makes installation easier and the analysis more reproducible. More details: http://mriqc.readthedocs.io/en/latest/docker.html

If you want to run it without containers you will need to install extra dependencies from this file: https://github.com/poldracklab/mriqc/blob/master/requirements.txt

**Comment by oesteban** [comment]
Hi @jnecus, if for some reason you can't use Docker or Singularity please let us know. Also, since 0.9.4 we dropped Python 2.

**Comment by jnecus** [comment]
@oesteban @chrisfilo  Running in Docker, seems be running fine. 

Couldn't get the standalone Pip installation to work.

Thanks for your advice.

Joe
