### ISSUE TITLE
3dskullstrip libGL.so.1?

### ISSUE THREAD

**Issue by mgxd** [poldracklab/mriqc#567]
Hi,

I have been running mriqc by converting docker --> singularity, but now that singularity 2.3 supports pulling directly from dockerhub, I'm giving that a try.

Command I'm running:
```
singularity exec -B $base:/mnt docker://poldracklab/mriqc:latest mriqc --participant_label $subj --verbose-reports --n_procs 10 --mem_gb 10 -w $WORKDIR $DATADIR $OUTDIR participant
```

Everything seems to be running fine, until getting to afni SkullStrip, where I run into a missing library causing that node to fail:
```
3dSkullStrip: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
```
I haven't tried using docker2singularity for `mriqc 0.9.6` yet, but `0.9.3` was working fine.

**Comment by mgxd** [comment]
After pulling the docker image and converting with `docker2singularity`, no issue is encountered - @vsoch potential bug?

**Comment by vsoch** [comment]
A few possibilities:

- If `3dSkullStrip` (and it's respective libraries) are somewhere in root's home (`/root`) as is typical of these images, and loading the shared library requires more than read permission, then the file is not found or openable because of that. The error message I would have expected is with regard to permission, but if an entire directory isn't readable at all, then it would come across as not found.
- If the library is defined in some environment variable that is not being properly passed (for example, see this [issue](https://github.com/singularityware/singularity/issues/719)) then the library isn't being found because it's not on the path.
- it could be some issue with a library that (for some reason) was not properly linked, or can't be properly linked given some permission. For example, with python wheel files python sometimes tries to unpackage them the first time you run, and if you don't have write, that can't happen (you get an error on the first run and then you might have a silent bug).

The approach I would take is to first figure out how/where the library is loaded in the working image, and then compare 1) locations, 2) environment variables to them, and 3) permissions for those things. My thinking is that one or more combinations of those things is seeing the error that you report. If you haven't been using singularity before 2.3, I'm not sure that we can attribute the error to the specific version, it very well could have been there with 2.2 too.

**Comment by mgxd** [comment]
@vsoch thanks for the response, I have been using singularity since 2.1, but this is the first time I've tried to run this image from pulling it straight from dockerhub (a really nice addition!). 

However, the conversion is not that same as using the docker container `docker2singularity` since I don't have root access when pulling/running the singularity. This is what you meant, yes?

**Comment by vsoch** [comment]
yes, it's not the same.

**Comment by chrisfilo** [comment]
FWIW `3dSkullStrip` is not located in `/root`

```
Singularity.poldracklab_mriqc_0.9.6-2017-06-03-99db97c9be2e.img> $ which 3dSkullStrip
/usr/lib/afni/bin/3dSkullStrip
```

It seems that even though the `pull` feature in singularity is amazing and the team is doing an outstanding job the feature is still a little rough around the edges. 

@mgxd I would suggest moving this issue to https://github.com/singularityware/singularity/issues since I am not sure what we could do within MRIQC to resolve it.

**Comment by vsoch** [comment]
@chrisfilo but where is the library? It would be very helpful if someone that uses this image could look into these issues, and figure out if it is related to the things above. We do our best to meet the needs of the users for Singularity, but without some guidance about "this is the /root of the problem" (har har I just made a pun) there isn't much we could do.

**Comment by chrisfilo** [comment]
The library is in `/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1`. Let me know if there is anything else I could help with.

I was not suggesting @mgxd or me should not be involved in investigating this issue. Just wanted to move it to singularity repo to expose it to broader singularity development community.

**Comment by mgxd** [comment]
@chrisfilo looks like `/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1` links to another file with limited permissions:
```
root@26412170ebeb:/# ls -l /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
lrwxrwxrwx 1 root root 14 Jan 26 00:17 /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 -> libGL.so.1.2.0
root@26412170ebeb:/# ls -l /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0 
-rw-r--r-- 1 root root 471680 Jan 26 00:17 /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
```

Perhaps this lack of permission results in it not being copied over?

**Comment by chrisfilo** [comment]
Could you confirm that `/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0` is present in the Docker image and the Singularity image created by `docker2singularity` but missing in the Singularity image created by `singularity pull`?

**Comment by mgxd** [comment]
@chrisfilo `/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0` is present in all images, but `/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1` is not present in the image generated from `singularity pull`

**Comment by vsoch** [comment]
here are the layers that singularity is dumping:

```
[u'sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4',
 u'sha256:8d47a6b78090d68b17786e22b92816f61974abea1ed267dd2ab6dc705b47495a',
 u'sha256:71cc1f897f9182469542083e31668fe2e9ef6a29bd34a642994098c792453823',
 u'sha256:7580416535f0c3dbdace804bed0213a3701debb79e34ea099f8849bf8dccb535',
 u'sha256:5bd848b357d35ec62bd6c13341b2193230c0d98155df403cee5b601c45e58c20',
 u'sha256:7700f5f11bcd210e6758a53d17dca9df692740731fc3e3805ac48e9f840a31d0',
 u'sha256:4404026f166c19230e6e66654ee7a558d538c20e8063192d36f13f26ddb0f3b5',
 u'sha256:1f75aa614800db092e54925a55a594b38d2d86637caa6f73b74c5efb433a6d94',
 u'sha256:37ed49cdeab67b45d3ddb44c25335bf6a7b13dbf48f09977061728017ac9edd0',
 u'sha256:fe74f1e296f66f8dbdea2d0f2344453dc660717a8bb502d0e62ba72d98ead94d',
 u'sha256:37773e97f2be732e3c478b498098b728e3c09b7ad7bd821202a4ed12bbe80c8b',
 u'sha256:3035235ca7e3b602ff8305dc50444232674143ca0968e8ea040a5a21b56972a7',
 u'sha256:34e9c7f09808029d900e60a3c239a70c6851c225bfdab24e6bf59042168cee08',
 u'sha256:6353ca1d3ed97743ee8a084d1d67356dc2f22807508907ec82131b338d1f2810',
 u'sha256:148a7d8ec5ddd119658f990e52dd4a2a2b11c92067c17afb51aaa783546d08d1',
 u'sha256:a144dee688a05a33cc6159fa173830645631c3c2e2cd39f79be2931f3399fc75',
 u'sha256:84e7d3c3db999d016da96fb629a9a2d557b38ff692b40ca89498866fb90f99c9',
 u'sha256:45da7bb9c607ee46c06e6c9d38cffe4a19b1f42a202dcb3698dce92eb42b011d',
 u'sha256:bd842a2105a862f62ba4ad726531029be49046c290307e9c07a688c89f4606e6',
 u'sha256:4a70713c436f2350e8a9f1c1e6c823290f331254c6c21d5657056499d8575608',
 u'sha256:63fe8c0068a811103c702452985368fc99014f83b5f0151cf631644f13f383b2',
 u'sha256:4daad8bdde31f5969d6a44800e993a911bed25853b2f89417b07ce7f0ac67714',
 u'sha256:b3e1c725a85f0953e81815b7c7aabfad9ebfd90af53f99248981282b8045d787']
```
and manifest for latest (v1):

```
{
    "container": "0a809f3915ae132eabddf66d390dc552b03d5c295ead9768450c226139b4576b",
    "parent": "5299ab26dec4a8a36a902a00ea215d5b52170d9cef59f068d3a1ba9d9e77fede",
    "created": "2017-06-03T19:09:32.682763788Z",
    "os": "linux",
    "container_config": {
        "Tty": false,
        "Cmd": [
            "/bin/sh",
            "-c",
            "#(nop) LABEL org.label-schema.build-date=2017-06-03T19:08:17Z org.label-schema.name=MRIQC org.label-schema.description=MRIQC - Automated Quality Control and visual reports for Quality Assesment of structural (T1w, T2w) and functional MRI of the brain org.label-schema.url=http://mriqc.readthedocs.io org.label-schema.vcs-ref=41313a5 org.label-schema.vcs-url=https://github.com/poldracklab/mriqc org.label-schema.version=0.9.6 org.label-schema.schema-version=1.0"
        ],
        "Volumes": null,
        "Domainname": "",
        "WorkingDir": "",
        "Image": "5299ab26dec4a8a36a902a00ea215d5b52170d9cef59f068d3a1ba9d9e77fede",
        "Hostname": "2866979c4d77",
        "StdinOnce": false,
        "Labels": {
            "org.label-schema.version": "0.9.6",
            "org.label-schema.schema-version": "1.0",
            "org.label-schema.vcs-ref": "41313a5",
            "org.label-schema.url": "http://mriqc.readthedocs.io",
            "org.label-schema.vcs-url": "https://github.com/poldracklab/mriqc",
            "org.label-schema.build-date": "2017-06-03T19:08:17Z",
            "org.label-schema.name": "MRIQC",
            "org.label-schema.description": "MRIQC - Automated Quality Control and visual reports for Quality Assesment of structural (T1w, T2w) and functional MRI of the brain"
        },
        "AttachStdin": false,
        "User": "",
        "Env": [
            "PATH=/usr/local/miniconda/bin:/opt/ants:/usr/lib/fsl/5.0:/usr/lib/afni/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "FSLDIR=/usr/share/fsl/5.0",
            "FSLOUTPUTTYPE=NIFTI_GZ",
            "FSLMULTIFILEQUIT=TRUE",
            "POSSUMDIR=/usr/share/fsl/5.0",
            "LD_LIBRARY_PATH=/usr/lib/fsl/5.0:",
            "FSLTCLSH=/usr/bin/tclsh",
            "FSLWISH=/usr/bin/wish",
            "AFNI_MODELPATH=/usr/lib/afni/models",
            "AFNI_IMSAVE_WARNINGS=NO",
            "AFNI_TTATLAS_DATASET=/usr/share/afni/atlases",
            "AFNI_PLUGINPATH=/usr/lib/afni/plugins",
            "ANTSPATH=/opt/ants",
            "LANG=C.UTF-8",
            "LC_ALL=C.UTF-8",
            "CRN_SHARED_DATA=/niworkflows_data"
        ],
        "Entrypoint": [
            "/usr/local/miniconda/bin/mriqc"
        ],
        "OnBuild": [],
        "AttachStderr": false,
        "AttachStdout": false,
        "OpenStdin": false
    },
    "architecture": "amd64",
    "docker_version": "1.9.1-circleci-cp-workaround",
    "config": {
        "Tty": false,
        "Cmd": null,
        "Volumes": null,
        "Domainname": "",
        "WorkingDir": "",
        "Image": "5299ab26dec4a8a36a902a00ea215d5b52170d9cef59f068d3a1ba9d9e77fede",
        "Hostname": "2866979c4d77",
        "StdinOnce": false,
        "Labels": {
            "org.label-schema.version": "0.9.6",
            "org.label-schema.schema-version": "1.0",
            "org.label-schema.vcs-ref": "41313a5",
            "org.label-schema.url": "http://mriqc.readthedocs.io",
            "org.label-schema.vcs-url": "https://github.com/poldracklab/mriqc",
            "org.label-schema.build-date": "2017-06-03T19:08:17Z",
            "org.label-schema.name": "MRIQC",
            "org.label-schema.description": "MRIQC - Automated Quality Control and visual reports for Quality Assesment of structural (T1w, T2w) and functional MRI of the brain"
        },
        "AttachStdin": false,
        "User": "",
        "Env": [
            "PATH=/usr/local/miniconda/bin:/opt/ants:/usr/lib/fsl/5.0:/usr/lib/afni/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "FSLDIR=/usr/share/fsl/5.0",
            "FSLOUTPUTTYPE=NIFTI_GZ",
            "FSLMULTIFILEQUIT=TRUE",
            "POSSUMDIR=/usr/share/fsl/5.0",
            "LD_LIBRARY_PATH=/usr/lib/fsl/5.0:",
            "FSLTCLSH=/usr/bin/tclsh",
            "FSLWISH=/usr/bin/wish",
            "AFNI_MODELPATH=/usr/lib/afni/models",
            "AFNI_IMSAVE_WARNINGS=NO",
            "AFNI_TTATLAS_DATASET=/usr/share/afni/atlases",
            "AFNI_PLUGINPATH=/usr/lib/afni/plugins",
            "ANTSPATH=/opt/ants",
            "LANG=C.UTF-8",
            "LC_ALL=C.UTF-8",
            "CRN_SHARED_DATA=/niworkflows_data"
        ],
        "Entrypoint": [
            "/usr/local/miniconda/bin/mriqc"
        ],
        "OnBuild": [],
        "AttachStderr": false,
        "AttachStdout": false,
        "OpenStdin": false
    },
    "id": "dcc5fbea4efd992f8df0e052fa24b6b7a54e417104c0d2007b92a265175cab87"
}
```

**Comment by chrisfilo** [comment]
Hey @vsoch I think I'm missing something. Are you just sharing this info to highlight a potential solution?

**Comment by vsoch** [comment]
nope just sharing information, in case it's helpful. For example, you might look at the layers being used and the ones singularity is using and say "aha, this is different!" or "look at that in the manifest, I didn't expect that to be parsed as such."

**Comment by chrisfilo** [comment]
I see - so your theory is that `docker pull` and `singularity pull` are getting different layers from Docker Hub?

**Comment by vsoch** [comment]
I don't know... I think it's most likely that a file is being extracted with incorrect permissions, as we've seen there are a lot of problems with things in `/root`, I'm looking around at manifests and layer ids (and trying to pull the image to take a look myself... it's still fat @chrisfilo ! :P)  and figured it wouldn't hurt to share in case it inspired anyone else's thinking.

**Comment by vsoch** [comment]
I think you could do like:

```
docker images --digests --all | grep mriqc
```
or use inspect to look at the manifest being used for the image for docker2singularity, and just for a sanity check, make sure they are the same

**Comment by chrisfilo** [comment]
I'm getting:

```poldracklab/mriqc                    0.9.6               sha256:c7a79735153b75fb0eee027cce958f8bb7f402b5ff1be7f264061e589a4eef5c   a395b7f4ccc0        2 weeks ago         4.61 GB```

which does not seem to correspond to any of the hashes in the data you shared...

**Comment by mgxd** [comment]
To recap:

The symlink file
```
/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 -> libGL.so.1.2.0
```
is not copied over, but the actually library
```
/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
```
is present in the container made by `singularity pull`.

**Comment by chrisfilo** [comment]
Moving this to singualrity repo to try to get more exposure from the singularity dev community: https://github.com/singularityware/singularity/issues/795

**Comment by soichih** [comment]
I am still having this problem when I run the latest container posted on the Dockerhub. Has the latest container pushed to Dockerhub after `RUN ldconfig` was added?

**Comment by oesteban** [comment]
Yes, it does (https://github.com/poldracklab/mriqc/blob/980c7209ba717e2cb06f2a23f77de1c756e5e708/Dockerfile#L122).

Can you double check that the tag you are using is 0.9.7? Thanks!

**Comment by soichih** [comment]
Thanks. I am running the container as following
`singularity run docker://poldracklab/mriqc input output participant --no-sub`

I've also tried the specific tag (docker://poldracklab/mriqc:0.9.7), but ran into the same problem. Maybe that's not the right way to specify the tag?

I am seeing following error message.

```
RuntimeError: Command:
3dSkullStrip -input /home/hayashis/git/app-mriqc/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..home..hayashis..git..app-mriqc..input..sub-0..anat..sub-0_T1w.nii.gz/skullstrip/sub-0_T1w_conformed_corrected.nii.gz -prefix sub-0_T1w_conformed_corrected_skullstrip.nii.gz
Standard output:
3dSkullStrip: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
```

If I do following, everything works.

```
singularity exec docker://poldracklab/mriqc bash -c "ldconfig && /usr/local/miniconda/bin/mriqc input output participant --no-sub"
```

**Comment by justbennet** [comment]
I will add some details on my testing to the newer issue #648
