### ISSUE TITLE
mriqc depends on WarpPointsFromStd from forked nipype

### ISSUE THREAD

**Issue by wtriplett** [poldracklab/mriqc#57]
Regarding this code in https://github.com/poldracklab/mriqc/blob/master/mriqc/workflows/anatomical.py#L180

This is provided in https://github.com/oesteban/nipype/tree/enh/FSLstd2imgcoords or as an open pull request to nipype https://github.com/nipy/nipype/pull/1398, but does not exist in official nypipe. I believe this will cause standard pip installs to not execute correctly.

**Comment by oesteban** [comment]
Yes, I maintain a branch called exp/mriqc in my fork of nipype with that interface. However, that precise part of the code is not very reliable (#56) so I'm migrating it to use nipype.

**Comment by chrisfilo** [comment]
BTW I'm happy to merge nipy/nipype#1398 as soon as the test pass.

**Comment by oesteban** [comment]
Yes, I know. We are stuck with #1407, this issue raised the need for less arbitrary use of the standard outputs.

Anyways, I never liked the procedure of projecting 3 coordinates and computing the mask over and over for every case. So we are changing that, and also FSL FIRST will be replaced with ANTs (which is a much better option IMHO)
