### ISSUE TITLE
Problems with SpikesMask when running more than one participant

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#579]
Running mriqc from inside singularity container created with docker2singularity and poldracklab/mriqc:latest from dockerhub.

Run params were:
```
Settings={'bids_dir': '/data/Xscanner/bids_mriqc_test', 'write_graph': True, 'testing': False, 
'hmc_afni': True, 'hmc_fsl': False, 'fft_spikes_detector': False, 'n_procs': 32, 'ants_nthreads': 8, 'output_dir': '/data/Xscanner/mriqc_single_node/output', 'work_dir': '/data/Xscanner/mriqc_single_node/work', 'verbose_reports': True, 'float32': False, 'ica': True, 'no_sub': True, 'email': '', 'fd_thres': 0.2, 'webapi_url': 'https://mriqc.nimh.nih.gov/api/v1', 'webapi_port': None, 'upload_strict': False, 'deoblique': False, 'despike': False, 'correct_slice_timing': False, 'report_dir': '/data/Xscanner/mriqc_single_nod
e/output/reports'}
```

Got error:
```
2017-06-28 16:12:34,261 workflow:INFO ***********************************
2017-06-28 16:12:34,261 workflow:ERROR could not run node: workflow_enumerator.funcMRIQC.ReportsWorkflow.SpikesMask.a21
2017-06-28 16:12:34,261 workflow:INFO crashfile: /data/Xscanner/mriqc_single_node/output/logs/crash-20170628-152645-varadajc-SpikesMask.a21-2ac87aca-2936-40ef-82f6-332605ce5a65.txt
2017-06-28 16:12:34,261 workflow:INFO ***********************************
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.9.6', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 304, in main
    workflow.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 590, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 279, in run
    report_nodes_not_run(notrun)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 101, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
```

I have attached the error file.

I do not get this error if I only run one participant at a time.

[crash-20170628-152645-varadajc-SpikesMask.a21-2ac87aca-2936-40ef-82f6-332605ce5a65.txt](https://github.com/poldracklab/mriqc/files/1109431/crash-20170628-152645-varadajc-SpikesMask.a21-2ac87aca-2936-40ef-82f6-332605ce5a65.txt)

**Comment by chrisfilo** [comment]
Could you share the content of the crash file? How much memory was
available?

**Comment by jvarada** [comment]
@chrisfilo Is there another one besides the text file I linked? The node had 32 cores, 121 GB memory.

**Comment by oesteban** [comment]
The crash file says the error is a keyboard interrupt signal (?)

**Comment by jvarada** [comment]
@oesteban I noticed that too, but this was a process sent to the HPC and running in the bg without any intervention from me.

The run script was (run.sh):
```
#!/bin/bash

module load singularity

singularity exec \
-B /gpfs:/gpfs \
-B /gs2:/gs2 \
-B /gs3:/gs3 \
-B /gs4:/gs4 \
-B /gs5:/gs5 \
-B /gs6:/gs6 \
-B /spin1:/spin1 \
-B /data:/data \
-B /scratch:/scratch \
-B /fdb:/fdb \
-B /lscratch:/lscratch \
/data/Xscanner/singularity_containers/mriqc.img \
mriqc \
--verbose-reports \
--write-graph \
--no-sub \
--nprocs 32 \
--mem_gb 121 \
--ica \
--work-dir /data/Xscanner/mriqc_single_node/work \
/data/Xscanner/bids_mriqc_test \
/data/Xscanner/mriqc_single_node/output  \
participant
```

The sbatch command was:
``sbatch --cpus-per-task=32 --mem=121g run.sh``

Below is the SLURM log for the run.


[slurm-44086720.txt](https://github.com/poldracklab/mriqc/files/1109696/slurm-44086720.txt)

**Comment by oesteban** [comment]
Maybe that's the signal used in your cluster when a job is killed for some
reason (eg memory)?

On Jun 28, 2017 10:54, "Jan Varada" <notifications@github.com> wrote:

@oesteban <https://github.com/oesteban> I noticed that too, but this was a
process sent to the HPC and running in the bg without any intervention from
me.

The run script was (run.sh):

#!/bin/bash

module load singularity

singularity exec \
-B /gpfs:/gpfs \
-B /gs2:/gs2 \
-B /gs3:/gs3 \
-B /gs4:/gs4 \
-B /gs5:/gs5 \
-B /gs6:/gs6 \
-B /spin1:/spin1 \
-B /data:/data \
-B /scratch:/scratch \
-B /fdb:/fdb \
-B /lscratch:/lscratch \
/data/Xscanner/singularity_containers/mriqc.img \
mriqc \
--verbose-reports \
--write-graph \
--no-sub \
--nprocs 32 \
--mem_gb 121 \
--ica \
--work-dir /data/Xscanner/mriqc_single_node/work \
/data/Xscanner/bids_mriqc_test \
/data/Xscanner/mriqc_single_node/output  \
participant

The sbatch command was:
sbatch --cpus-per-task=32 --mem=121g run.sh

Below is the SLURM log for the run.

slurm-44086720.txt
<https://github.com/poldracklab/mriqc/files/1109696/slurm-44086720.txt>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/poldracklab/mriqc/issues/579#issuecomment-311737818>,
or mute the thread

**Comment by jvarada** [comment]
Contacted the HPC people and the interrupt is not being sent by the HPC itself.

Ran the singularity container in debug mode, and am getting the following error right before the SpikesFinder node fails:
```
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 1031988 max
```
According to HPC staff, the instance I'm allocating is not exceeding max cpus/mem capacity, so this is happening within the container itself. Any ideas on how to get around it?

**Comment by oesteban** [comment]
@jvarada thanks a lot for digging into this.

I have no ideas right now. I can come back to this topic by the end of next week. My first guess is that the `SpikesFinder` node is spawning new processes, beyond the limit of 32 you set.

I've tried to find that node, and maybe your version of mriqc is a bit outdated: [here](https://github.com/poldracklab/mriqc/commit/0245fe44e0cd32464492cef3cb79d186df54427d) we removed the SpikesFinder node.

Updating should do.

Nevertheless, I'll come back to this issue by the end of next week.

**Comment by jvarada** [comment]
@oesteban Do you have a build of 0.9.7-rc1 in dockerhub? I only see up to 0.9.6.

**Comment by oesteban** [comment]
@jvarada Sorry for the delay. I will brew a 0.9.7-rc1 when #581 is merged :)

Thanks!

**Comment by oesteban** [comment]
@jvarada: [this build](https://circleci.com/gh/poldracklab/mriqc/1885) will push the tag `0.9.7-rc1` to docker hub if successful.

**Comment by oesteban** [comment]
Waiting for #585

**Comment by jvarada** [comment]
@oesteban Still getting the spikeMask node error. I've attached the singularity/mriqc hpc log file.

[slurm-45331362.txt](https://github.com/poldracklab/mriqc/files/1154257/slurm-45331362.txt)

**Comment by oesteban** [comment]
@jvarada Thanks, now this error makes more sense. Apparently the mask is empty.

**Comment by jvarada** [comment]
@oesteban If I understood the log correctly, the mask node is failing due to the OpenBLAS threading issue, and the subsequent node that depends on it throws the error since the mask didn't get generated.

**Comment by oesteban** [comment]
You're right. Might be needed to set OMP_NUM_THREADS.

I suspect several SpikesMask are being run simultaneously in the same node, requesting too many threads (numpy parallelization).

**Comment by oesteban** [comment]
Could you try 0.9.7-rc3 and see if that solved the problem? Thanks!

**Comment by jvarada** [comment]
@oesteban Nodes ran without any OpenBLAS issues, and the SpikesMask node didn't throw any error messages. It does seem it didn't find a mask for the plotting part at the end though?

Report attached.
[slurm-45372624.txt](https://github.com/poldracklab/mriqc/files/1156619/slurm-45372624.txt)

**Comment by oesteban** [comment]
Those are warnings, I think they are unrelated to this issue (will follow-up in #589)
