### ISSUE TITLE
Authentication failing on submission to the WebAPI

### ISSUE THREAD

**Issue by oesteban** [poldracklab/mriqc#594]
```
2017-07-20 06:20:07,168 interface:WARNING QC metrics failed to upload. Status 401: {"_error": {"code": 401, "message": "Please provide proper credentials"}, "_status": "ERR"}
```

**Comment by oesteban** [comment]
@chrisfilo this is maybe why we are getting less measures lately
@rwblair any chance that something changed in the Web API end?

**Comment by chrisfilo** [comment]
Can you reproduce this locally? Did you try 0.9.6?

**Comment by oesteban** [comment]
@rwblair disregard this. It is my fault. Thanks @chrisfilo for walking me to the solution.

**Comment by oesteban** [comment]
Using the official `0.9.7-rc5` it worked. Nothing to look at here. Thanks and sorry for the noise.

**Comment by marcelzwiers** [comment]
I also get this error

**Comment by chrisfilo** [comment]
Are you using Docker or Singularity?

**Comment by marcelzwiers** [comment]
Neither, just did pip install

Op vr 15 jun. 2018 om 11:09 schreef Chris Filo Gorgolewski <
notifications@github.com>:

**Comment by marcelzwiers** [comment]
2018-06-15 10:58:23,131 interface:WARNING QC metrics upload failed to create an ID for the record uplOADED. rEsponse from server follows: {"_error": {"message": "Please provide proper credentials", "code": 401}, "_status": "ERR"}
2018-06-15 10:58:23,132 interface:WARNING QC metrics failed to upload. Status 401: {"_error": {"message": "Please provide proper credentials", "code": 401}, "_status": "ERR"}

mriqc --version
mriqc v0.11.0

**Comment by chrisfilo** [comment]
To avoid the authentication issue you need to disable the QC metric
crowdsourcing on the command line. See --help for details.

Best,
Chris

PS Apologies for brevity and potential typos. This message was composed on
a phone.

**Comment by marcelzwiers** [comment]
You mean using --no-sub (turn off submission of anonymized quality metrics
to MRIQC's metrics repository)? Sure I won't get this error then, but I
thought anyone could upload their QC metrics?

Op vr 15 jun. 2018 om 11:39 schreef Chris Filo Gorgolewski <
notifications@github.com>:

**Comment by oesteban** [comment]
Oh, you are right Marcel. We bake the authentication token in when building
the docker image, and seemingly we don't for the pypi package. I'll have a
look and see if that can easily be done.

But for now, I don't think you'll be able to share your IQMs when run as a
python package :(.
