### ISSUE TITLE
Error filtering datasets using the participant/session/run tags

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#601]
If I try to select just using the --session-id tag or with both the --participant_label and --session-id tags it says either the BIDS directory is non-BIDS compliant or it doesn't find any files. Using just the --participant_label tag to filter out just by subject ID or running the whole dataset without filtering works fine.

**Comment by oesteban** [comment]
I'll have a look. Probably missing parts from #504 .

**Comment by jvarada** [comment]
@oesteban I can look into this.

**Comment by oesteban** [comment]
That'd be lovely! Thanks!!!
