### ISSUE TITLE
Special considerations for not-EPI data?

### ISSUE THREAD

**Issue by stjep** [poldracklab/mriqc#604]
Are there any special considerations or potential problems when running BOLD data using a not-EPI sequence through the standard (and additionally ICA/FFT-spike) routines? I've been testing out spiral-in BOLD data. Am I right in assuming that everything should function about the same?

On that note, the output has *EPI mean session* and *EPI SD session* as headers, but this is not the case for non-EPI data.

**Comment by chrisfilo** [comment]
It should work AFAIK, but we love to hear how did it go.

The report captions should be changed but to mention EPI.

**Comment by oesteban** [comment]
Opened #607 for the labels.

@stjep please let us know if it worked OK on your spiral data, thanks a lot!
