### ISSUE TITLE
MRIQC 0.9.7: mriqc.report:WARNING Building bold report: no exclude index was found

### ISSUE THREAD

**Issue by vsteiger** [poldracklab/mriqc#609]
hey,

I tried to re-run MRIQC on a data set that previously ran in version 0.9.3.

The data set contains bold and T1w data has 3 sessions and 80 subjects.

After submitting this:

`sudo docker run -v /home/ubuntu/projects_docker/pr1:/data -v /home/ubuntu/projects_docker/pr1:/scratch -w /scratch poldracklab/mriqc:latest /data /scratch/out participant -w /scratch/work --participant_label 01 02 03 --no-sub`

I'm running into this error:

`2017-07-28 07:39:06,709 mriqc.report:WARNING Building bold report: no exclude index was found`

Any ideas on this?

**Comment by oesteban** [comment]
Hi @vsteiger, that is a WARNING, not an error. For some reason, the steady state was not computed. Are you reusing the work folder from a previous computation?

**Comment by tientong98** [comment]
Hi,

I got the same warning:

`2018-04-10 16:55:09,068 mriqc.report:WARNING Building bold report: no exclude index was found`

and this is the first time I run MRIQC on this dataset, so I did not reuse the work folder. How would this (not computing the steady state) affect the IQMs, and how do I fix this?

Below is the command I use:

```singularity run -H /singularity/path \
-B /data/path/:/mnt \
/singularity/image/path/mriqc-latest.simg \
/mnt/BIDS/path \
/mnt//BIDS/derivatives \
participant --participant-label 01 \
-m bold --task-id stopsignal --no-sub \
-w /mnt//BIDS/derivatives --report-dir /mnt//BIDS/derivatives \
--verbose-reports --write-graph \
--deoblique  --despike --correct-slice-timing \
--n_procs 8 --mem_gb 22500```

**Comment by MengYunWang** [comment]
Hi, I encountered the same issue today. Also, it is my first time running the MRIQC, version 0.16.1.
