### ISSUE TITLE
CSV files missing from group level outputs

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#610]
https://circleci.com/gh/poldracklab/mriqc/1912#artifacts/containers/0

Was this intentional?

**Comment by oesteban** [comment]
I can see them under the out/ folder (?)

https://1912-49015296-gh.circle-artifacts.com/0/home/ubuntu/scratch/out/T1w.csv
https://1912-49015296-gh.circle-artifacts.com/1/home/ubuntu/scratch/out/bold.csv

**Comment by chrisfilo** [comment]
My bad. It's missing on openfmri S3, but for a different reason.
