### ISSUE TITLE
newer dockerhub image

### ISSUE THREAD

**Issue by jvarada** [poldracklab/mriqc#624]
Is there any way to get a newer dockerhub image after #612 was merged? Or are there development branch docker images being generated somewhere?

**Comment by oesteban** [comment]
I can brew a release candidate, that would generate a new docker image. Would that work for you?

**Comment by jvarada** [comment]
Yes, that would be fine. For some reason I tend to have problems mounting directories from our HPC onto a singularity image built from containers I generate locally, but with the ones you guys provide everything works fine.

**Comment by oesteban** [comment]
A new 0.9.7-0 tag will be generated upon success of https://circleci.com/gh/poldracklab/mriqc/1924

**Comment by oesteban** [comment]
Okay, we are now at 0.10.4, so this can be closed 👍
