### ISSUE TITLE
Failed MRIQC Reports

### ISSUE THREAD

**Issue by sadevp** [poldracklab/mriqc#626]
MRIQC failed for the following three datasets in OpenNeuro.

https://openneuro.org/datasets/ds000007/versions/00001
https://openneuro.org/datasets/ds000011/versions/00001?app=MRIQC&version=33&job=175bb11d-3ee6-47ee-a7ca-9cc385ab16a6
https://openneuro.org/datasets/ds000052/versions/00001?app=MRIQC&version=33&job=5720deb7-deef-4065-b86c-d58f0e49ec48

**Comment by sadevp** [comment]
UPDATE:

Still failing:

https://openneuro.org/datasets/ds000007/versions/00001?app=MRIQC&version=33&job=f7b5739d-362e-4d11-accf-d50eac042a64

Still **running** since 8.17:
https://openneuro.org/datasets/ds000011/versions/00001?app=MRIQC&version=33&job=175bb11d-3ee6-47ee-a7ca-9cc385ab16a6

Succeeded after re-running:
https://openneuro.org/datasets/ds000052/versions/00001?app=MRIQC&version=33&job=5720deb7-deef-4065-b86c-d58f0e49ec48

**Comment by oesteban** [comment]
Hi @sadevp, thanks for the reports.

- [x] We already had the error of ds007 under the radar (see #621).
- [ ] I'll check on ds011 tomorrow.
- [x] I ran ds052 yesterday without errors, so it does not surprise me that it worked after re-running.

I'll keep you updated. I'll leave this open until we triage ds011.

**Comment by oesteban** [comment]
DS011 was already diagnosed (failing because of #623). One subject seems to have CRC errors.
