### ISSUE TITLE
Dataset ds000140 Failing to Upload

### ISSUE THREAD

**Issue by sadevp** [poldracklab/mriqc#627]
Re: the dataset here: https://openfmri.org/dataset/ds000140/ 

It consistently stalls while uploading to OpenNeuro and then fails after repeated attempts to upload (please see attached screenshots). 

![screen shot 2017-08-24 at 12 07 20 pm](https://user-images.githubusercontent.com/26071772/29683882-d385a30e-88c4-11e7-9e58-4cd5bfcd9450.png)

**Comment by chrisfilo** [comment]
Wrong repository...
