### ISSUE TITLE
Add examples of reports to documentation

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/mriqc#63]
Preferably high res rather than the ones we generate on CircleCI

**Comment by oesteban** [comment]
Depends on #34

**Comment by chrisfilo** [comment]
I would add screenshots of existing reports and update the docs if/when we
switch to interactive reports. Everybody likes a pretty picture!

**Comment by oesteban** [comment]
Sure! But I guess it does not make much sense to do this before we switch to html/interactive, and then again... right?

**Comment by vsoch** [comment]
+1 pretty picture. with colors and interactivity!!
