### ISSUE TITLE
Trouble with Philips precise values

### ISSUE THREAD

**Issue by parekhpravesh** [poldracklab/mriqc#640]
Hello,

When running mriqc on data obtained from a Philips scanner, the images sort of "break down"

![sub-01_with precise](https://user-images.githubusercontent.com/8792123/30097816-19e4c298-92fd-11e7-9392-9fe00eccdfd3.png)

When running the same subject with Philips precise set to no (https://www.nitrc.org/forum/message.php?msg_id=20293), the results are better, if not completely correct.

![sub-01_without precise](https://user-images.githubusercontent.com/8792123/30097914-7ab7b1ac-92fd-11e7-9e3f-de512b2849be.png)

The intensity ranges (as shown in mricron) are:

With Philips precise:      1334.0183 to 70110.0781
Without Philips precise: 24.9538    to 1311.4633

Since dcm2niix saves the information (in the .json file) about which values are being used, perhaps this can be read off in the beginning and data can be re-scaled if needed? Also, it seems that even after re-scaling there are problems (a few examples marked in the second image). Could something be going wrong when casting the data from one type to another? 

Look forward to your thoughts on this.

NB: We have used an older release for this run running on Python 2.7...we would be upgrading soon (if that makes a difference)

Thanks a lot for your time
Pravesh

**Comment by oesteban** [comment]
Hi Pravesh, thanks a lot for this information.

It seems that MRIQC is truncating the long integer, I'll have a look at that (#641).

The second example looks to me more like an AFNI failure. We have a couple of issues open regarding to that (#552, #554). If you shared your data with me, I could give it a try. Let me know if it is possible.

**Comment by parekhpravesh** [comment]
Hi @oesteban, I am emailing you the data from a single subject (corresponding to the snapshots above). Thanks a lot for your help!

**Comment by oesteban** [comment]
Just tried to replicate with your data and it seems we may have fixed this problem. The masks still fail, though, please follow up on #275.

**Comment by parekhpravesh** [comment]
Hello, I thought this issue had been resolved years ago...has the problem come back?

**Comment by oesteban** [comment]
Sorry for the noise. I was trying to minimize the damage of the stale bot closing issues. Thanks for the heads up and please disregard this notification.
