### ISSUE TITLE
Permissions prevent unprivileged user from running MRIQC Singularity image

### ISSUE THREAD

**Issue by justbennet** [poldracklab/mriqc#647]
This issue was substantially reported at the mriqc google group.
https://groups.google.com/forum/#!topic/mriqc-users/TY_nH6XLQyQ

I am under the impression that the project would like to support use of MRIQC as a Singularity application.  Please let me know if that is not so.

The bundled Miniconda leaves some files in the Docker image owned by root and with permissions set to 0600.  I believe Docker runs as root, and in the Docker environment, this is not a problem (or I presume you would have noticed).  However, when the Docker container is converted to Singularity to run using user credentials on a cluster, this results in an read error and Traceback.

The output running as myself:
```
$ singularity exec -B /home/bennet/Projects/mpeckins/MRIQC/ds008_R2.0.0:/data:ro -B $PWD/out:/out \
    mriqc.simg  mriqc --help
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 6, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
[ .... elided for brevity ... ]
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1861, in get_metadata
PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info'
```

The output running with sudo:
```
$ sudo singularity exec -B /home/bennet/Projects/mpeckins/MRIQC/ds008_R2.0.0:/data:ro -B $PWD/out:/out \
    mriqc.simg  mriqc --help

usage: mriqc [-h] [--version]
             [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
             [--session-id SESSION_ID [SESSION_ID ...]]
             [--run-id RUN_ID [RUN_ID ...]] [--task-id TASK_ID [TASK_ID ...]]
[ ... elided for brevity ... ]
```

I believe that this might be fixed inside the Docker container by adding to the Dockerfile at line 93,
```
    chmod -R a+rX /usr/local/miniconda && \
```
prior to the line that sets the execute bit for all the files in `/usr/local/miniconda/bin`.

I am running this on the OpenfMRI ds008 dataset, and if I use this Singularity `.def` file
```
Bootstrap: docker
From: poldracklab/mriqc:latest

%post
chmod -R a+rX /usr/local/miniconda
mkdir /data
```
MRIQC runs.  If I leave out the `chmod`, root is required.

I hope this report is adequate.  If more information is needed, please let me know.  Sorry if to much detail is included, or if this is out of scope.

**Comment by oesteban** [comment]
Hi @justbennet thanks for this report, and the verbosity is very much appreciated.

I'd say this issue is very much related to https://github.com/singularityware/singularity/issues/571

However, your proposed solution seems pretty reasonable, so let's also try that (change to line 93 of the Dockerfile).

Could you please submit a PR to change that line?

Thanks very much.

**Comment by oesteban** [comment]
This should be now fixed with @justbennet's contribution.
