### ISSUE TITLE
Clarify docs on FWHM

### ISSUE THREAD

**Issue by nicholst** [poldracklab/mriqc#665]
As a new user, simply handed a set of HTML reports from MRIQC, I was confused when I clicked through to the [FWHM documentation](http://mriqc.readthedocs.io/en/latest/iqms/bold.html#iqms-fwhm) that suggests that `fwhm_{x,y,z}` is a "structural" summary, described under  "[Measures for the structural information](http://mriqc.readthedocs.io/en/latest/iqms/bold.html#measures-for-the-structural-information)", leading me to believe that I the boxplot of FWHM's I was examining was for the structural MRI.

Won't it be clearer to call this collection of measures "Measures for the spatial information" in parallel to the heading "[Measures for the temporal information](http://mriqc.readthedocs.io/en/latest/iqms/bold.html#measures-for-the-temporal-information)" instead of "Measures for the structural information"?

**Comment by oesteban** [comment]
That makes a lot of sense. Will change ASAP. Thanks!

**Comment by malywladek** [comment]
Is FWHM reported in [mm] as it is indicated in report or in [voxels] as it is stated in manual?
