### ISSUE TITLE
Error with group-level analysis on HPC using singularity image of MRIQC 0.10.0

### ISSUE THREAD

**Issue by gmrosenb** [poldracklab/mriqc#675]
Hi,

I'm running mriqc version 0.10.0 on an HPC cluster with a BIDS dataset including both structural and functional runs. The subject-level analysis ran successfully, and I am trying to run the group level, but am getting an error message and I'm not seeing any other posts related to this error. Any insights would be appreciated!

Here is the input:

`singularity exec /beegfs/work/public/singularity/mriqc-0.10.0.img mriqc /beegfs/work/hartley/projects/MBMFDev/data/BIDS_MBMF/ /beegfs/work/hartley/projects/MBMFDev/data/mriqc/out/ group`

Here is the output error:

`Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.10.0', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 381, in main
    out_file=out_html)
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/reports/group.py", line 168, in gen_html
    'boxplots.js'))).read(),
  File "/usr/local/miniconda/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 7465: ordinal not in range(128)
`

**Comment by kevmanderson** [comment]
I had this same issue. On my cluster it was due to conflicting python paths. 

I resolved the problem by unsetting the PYTHONPATH environment variable:
unset PYTHONPATH

Alternatively, working with a clean install of anacondas3 might fix this.

**Comment by oesteban** [comment]
Both solutions may work for other users having the same issues. Bottom line is that we changed the underlying nipype version from v. 0.10.0 to 0.10.1 and this decoding error is one of the bugfixes.

Therefore, a clean install of anaconda would upgrade the version of niworkflows (and in fact update nipype).

Updating the singularity image implicitly updates niworkflows.

Finally, the suggestion of @kevmanderson of unsetting `$PYTHONPATH` is particularly relevant with singularity. With a singularity image of mriqc-0.10.1 working with a python environment with an outdated niworkflows would lead to this problem if `$PYTHONPATH` is set.

Thanks very much for posting this issue, and glad the latest release worked well.

**Comment by gmrosenb** [comment]
@oesteban thank you for clarifying! I'm new to to docker and singularity, so this helps me understand the issue better.
