### ISSUE TITLE
Running ICA only in some images

### ISSUE THREAD

**Issue by mainux** [poldracklab/mriqc#676]
Hi!
I'd like to know if it is possible to run ICA only in some functional images, instead of in all the functional images that contains the BIDS directory. We have several AP and PA acquisitions with only 6 images, and they are generating a lot of errors because MRIQC is trying to compute ICA on them.

Thank you for your help!

**Comment by oesteban** [comment]
Hi @mainux, sorry for the delay.

Right now there is no way to do that explicitly. Indirectly, you can use the ``--session-id``, ``--task-id``, ``--run-id`` selectors to run with and without ``--ica`` correspondingly.

**Comment by mainux** [comment]
Ok, thanks! 

I'll try 

Maite Termenon 
Postdoctoral Researcher at BCBL 
Neurobiology of language group 
www.bcbl.eu 

Legal disclaimer/Aviso legal/Lege-oharra: www.bcbl.eu/legal-disclaimer

**Comment by oesteban** [comment]
Hi @mainux, we release version 0.12.1 fixing problems with BIDS filters (`--task-id`, `--run-id`, etc.).

Please reopen if you experience this issue again.
