### ISSUE TITLE
MRIQC doesn't ignore hidden files

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/mriqc#682]
Here is an error from an MRIQC log:

2018-01-19 19:34:32,673 workflow:INFO Executing node provenance.a5 in dir: /work/03201/jbwexler/stampede2/ds000257_R1.0.0/work/workflow_enumerator/funcMRIQC/ComputeIQMs/_in_file_..work..03201..jbwexler..stampede2..ds000257_R1.0.0..sub-18..func..sub-18_task-collaborativetask_run-06_bold.nii.gz/provenance
2018-01-19 19:34:32,676 workflow:INFO Traceback (most recent call last):
 File “/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py”, line 52, in run_node
   result[‘result’] = node.run(updatehash=updatehash)
 File “/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py”, line 372, in run
   self._run_interface()
 File “/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py”, line 482, in _run_interface
   self._result = self._run_command(execute)
 File “/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py”, line 613, in _run_command
   result = self._interface.run()
 File “/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py”, line 1081, in run
   runtime = self._run_wrapper(runtime)
 File “/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base.py”, line 1029, in _run_wrapper
   runtime = self._run_interface(runtime)
 File “/usr/local/miniconda/lib/python3.6/site-packages/mriqc/interfaces/common.py”, line 96, in _run_interface
   nii = nb.load(self.inputs.in_file)
 File “/usr/local/miniconda/lib/python3.6/site-packages/nibabel/loadsave.py”, line 48, in load
   filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of “/work/03201/jbwexler/stampede2/ds000257_R1.0.0/sub-11/anat/._sub-11_T1w.nii.gz”
Interface ConformImage failed to run.

**Comment by oesteban** [comment]
Weird, that shouldn't be even grabbed by pybids. I'll make sure we update pybids for next release.

**Comment by chrisfilo** [comment]
Out of curiosity - where are these files coming from?

Best,
Chris

**Comment by jbwexler** [comment]
It was accidentally included by the submitter. There were also many .DS_Store files, but those didn't produce any errors.

**Comment by effigies** [comment]
INCF/pybids#121 should fix this issue. I've added exclusions for dot files/directories.

**Comment by oesteban** [comment]
This should be fixed with #700 . Please reopen if it happened again.
