### ISSUE TITLE
MRIQC can't handle large dataset in Docker

### ISSUE THREAD

**Issue by malywladek** [poldracklab/mriqc#683]
Hi,
I am trying hard to run mriqc on my dataset of ~500 runs of fmri and 40 T1s. 
I've got Docker 17.12 running on iOS 10.13.1. Docker is set up to 4 CPUs and 16 GB. I tried latest version of mriqc and 0.9.2.
Mostly I enter following command:
_caffeinate -s docker run -it --rm -v /Users/bkossows/Lokalne/ciop_all:/data:ro -v /Users/bkossows/Lokalne/ciop_all_output:/out poldracklab/mriqc:latest /data /out participant_
For the latest version of mriqc I obtain only T1 reports. For older one I got T1s and 139 bold reports. Program hangs up or exits with no general error nor log. I attach my bash log for the most successful run with 139 outputs. 
I've noticed that memory usage goes up from 2-4 GB at the beginning to all 16 GB at the end. Each time there are some warnings concerning pyplot.
Please let me know what is going on.

[end_of_bash_log.txt](https://github.com/poldracklab/mriqc/files/1685473/end_of_bash_log.txt)

**Comment by oesteban** [comment]
Hi @malywladek,

As you were suspecting, this looks like memory issues. Fortunatelly, the nipype framework that mriqc uses has advanced significantly since the latest release of nipype. Many of those advances are related to memory issues.

I've opened #692 to address this.

**Comment by oesteban** [comment]
For now, what I would do is running subjects separately (using the `--participant-label` flag).

**Comment by oesteban** [comment]
Hi @malywladek, did you manage to run MRIQC on your dataset?

**Comment by malywladek** [comment]
Oscar,
yes I managed to run it in trunks of 10-15 subjects. Behavior of the container is strange when it comes to memory allocation. Would You rather analyze subjects one-by-one in separate containers or grouped on a server?
B.

**Comment by oesteban** [comment]
Hi @malywladek sorry for the delay in response.

We generally recommend running 4 subjects in parallel at most. Hopefully, the upcoming release will address your memory issues. Also, we've optimized the workflows so that now they run quite fast (meaning, no need for trying to run many subjects simultaneously).

Please reopen if you still experience memory issues.
