### ISSUE TITLE
ERROR (nifti_image_read)

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/mriqc#693]
Excerpt:

Standard error: ++ 3dTqual: AFNI version=AFNI_17.3.03 (Nov 9 2017) [64-bit] ** ERROR (nifti_image_read): short header read '/usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/fMRI_HMC_afni/_in_file_..snapshot..data..sub-08..func..sub-08_task-collaborativetask_run-01_bold.nii.gz/motion_correct/sub-08_task-collaborativetask_run-01_bold_volreg.nii.gz' *** Can't open dataset /usr/local/src/mriqc/work/workflow_enumerator/funcMRIQC/fMRI_HMC_afni/_in_file_..snapshot..data..sub-08..func..sub-08_task-collaborativetask_run-01_bold.nii.gz/motion_correct/sub-08_task-collaborativetask_run-01_bold_volreg.nii.gz Return code: 1 

Please see the MRIQC logs here for more details: https://openneuro.org/datasets/ds001228/versions/00001?app=MRIQC&version=61&job=5a876b909259cd00018b981e

**Comment by oesteban** [comment]
Is this happening after #687?

**Comment by chrisfilo** [comment]
yes

**Comment by chrisfilo** [comment]
Got another one: https://openneuro.org/datasets/ds001239/versions/00001?app=MRIQC&version=64&job=74268b13-7610-4f3a-a541-c2409862cd4c

**Comment by chrisfilo** [comment]
Related to #662
