### ISSUE TITLE
EEG Quality Control?

### ISSUE THREAD

**Issue by vsoch** [poldracklab/mriqc#718]
hey @poldracklab/owners ! I know mriqc is for MRI, but since this it's also state of the art for QA I wanted to open up discussion (and get your thoughts on) what are best practices for EEG QA. I've talked to a lot of labs that still use Matlab (and possibly because Matlab does have a one up with respect to signal processing, this won't change for a while?) but I think a bids-app that is for the processing of EEG QA would be fairly useful for the neuroimaging community. Matlab and the lovely licensing it requires needs to not be a thing that we have to deal with on a shared resource anymore! I know that MNE --> https://github.com/mne-tools/mne-python is a nipy tool for EEG processing, would discussion around bids-ification of that be a place to start? Is there another tool (I just saw this on Frontiers --> https://www.frontiersin.org/articles/10.3389/fninf.2018.00030/full) that might be better? I'll ping some of the users that I'm chatting with on here to join the discussion. :phone:

**Comment by chrisfilo** [comment]
Hey @vsoch. https://neurostars.org might be a better forum for such a broad discussion. I don't know the answers to your questions, but happy to ask around.

**Comment by vsoch** [comment]
Thanks! I totally had forgotten about neurostars, here is the post --> https://neurostars.org/t/quality-analysis-for-eeg-container/1785

I got the error message "only two links per new user" or something like that. Terrible.
