### ISSUE TITLE
Saving user ratings to a local file / database

### ISSUE THREAD

**Issue by marcelzwiers** [poldracklab/mriqc#719]
So this is not an issue but a feature request. Currently, at the bottom of the reports there is the possibility to upload user ratings to a nimh server. That is fine of course, but it would be very useful if these ratings could also be made accessible to non-nimh researchers, e.g. by saving these ratings also to a local file / database / server.

**Comment by oesteban** [comment]
Hi @marcelzwiers, I'm really glad you run all these extra miles all alone!. You can query the web-API and fetch your ratings and others, it is open to anyone :). We don't have any examples on how to do it yet, but should be pretty straightforward to do based off this: https://github.com/poldracklab/mriqc/blob/95cb70a3d4059d92d57b44a7763a9700dd9d4ef4/notebooks/MRIQC%20Web%20API.ipynb

You can visit the example API here: https://mriqc.nimh.nih.gov/, if you go down, you'll find the ratings endpoint (`/rating`). I can see we have 269 at this moment!.

Please let me know if this answers your feature request. Maybe, to replay it in full, I could just add a command to mriqc that actually pulls those data into a local file as you propose.
