### ISSUE TITLE
Wrong doi of FWHM

### ISSUE THREAD

**Issue by LRZuo** [poldracklab/mriqc#722]
On the user manual about IQMs (i.e., http://mriqc.readthedocs.io/en/latest/iqms/t1w.html), the reference doi of FWHM is wrong. 

Forman SD et al., Improved assessment of significant activation in functional magnetic resonance imaging (fMRI): use of a cluster-size threshold, Magn. Reson. Med. 33 (5), 636–647, 1995. doi:10.1016/j.neuroimage.2006.03.062.

**Comment by oesteban** [comment]
Thanks for reporting!
