### ISSUE TITLE
ABIDE classifications

### ISSUE THREAD

**Issue by eduardklap** [poldracklab/mriqc#728]
Hi,

I am working on a revision of this paper: (https://www.biorxiv.org/content/early/2018/03/21/278358) in which we predict quality ratings using FreeSurfer output. One of the things we want to do in this revision is to look how our scores relate to MRIQC metrics.

What I am now searching for is a list of binary predictions using MRIQC for the ABIDE dataset. So the 'performance measured in the outer cross-validation loop on the ABIDE dataset' as described in the PLOS One paper.
I found the manual ratings for ABIDE on the Github (https://github.com/poldracklab/mriqc/blob/master/mriqc/data/csv/y_abide.csv) and the binary predictions for the DS030 I think (https://github.com/poldracklab/mriqc/blob/master/mriqc/data/csv/mclf_run-20170703-190702_mod-rfc_ver-0.9.7.clf-3.3_class-2_cv-loso_data-test_pred.csv), but can you point me to a file with binary predictions for ABIDE? So this will probably contain 10 scores for every individual from the 10-fold training.

Thanks in advance.

**Comment by oesteban** [comment]
As discussed over email:

> You are right on both files. I did not store the binary predictions for ABIDE, that would've been interesting. However, following the documentation (http://mriqc.readthedocs.io/en/latest/classifier.html), it should be pretty straightforward to get those (passing in the features for ABIDE - https://github.com/poldracklab/mriqc/blob/master/mriqc/data/csv/x_abide.csv as evaluation set).

Please reopen if you find any problems running the classifier on the ABIDE features.

**Comment by eduardklap** [comment]
Thank you Oscar! Will probably manage.
As discussed over email: got some trouble running mriqc on our cluster, but really enjoying the output now that it works! Thank you for all the effort put into this tool!

Best Eduard
