### ISSUE TITLE
Boxplots' whiskers description

### ISSUE THREAD

**Issue by andersonwinkler** [poldracklab/mriqc#729]
Hi all,

Congrats for the great work on MRIQC!

Could you add to the documentation what the whiskers in the boxplots represent? We'd think it'd be 1.5 IQR but when we calculate it doesn't seem to be the case. Visual inspection leaves doubts and we don't find this written anywhere in the docs...

Thanks!

Anderson

**Comment by oesteban** [comment]
Thanks for reporting. Will do asap.
