### ISSUE TITLE
Failure in SpatialNormalization step with MRIQC v0.14.2 and Docker image

### ISSUE THREAD

**Issue by DavidEWarrenPhD** [poldracklab/mriqc#747]
I'm trying the latest version of MRIQC (v0.14.2) through the Docker image (pulled today, 8/21/18).  Processing of all participants fails at the SpatialNormalization step — a sample crash log is below.

MRIQC was called as follows for a single participant.
```
docker run     -it     --rm     -v /mnt/warren_lab/datasets/devcog/data/bids:/data:ro     -v /bulk/projects/mriqc:/out poldracklab/mriqc:latest /data /out participant --participant-label somelabel --session-id 1 -m T1w -w /out/work
```

The problem seems to derive from an empty mask after the warp from individual anatomy to MNI.  Specifically, antsRegistration (wrapped by nipype/niworkflows) is used to warp the (unremarkable and non-empty) brain mask from binarized/sub-some_label_ses-1_acq-main_T1w_conformed_calc_thresh.nii.gz to MNI space for a sanity check of the warp (by checking overlap with the MNI brain mask), but the resulting MNI-space mask is empty.

The ANTs warp from individual anatomy to MNI is decent, and I've tested the mask warp using a local version of ANTs with the same result (i.e., an empty mask after warping).  I'm stumped.  Any thoughts?

```
$ cat crash-20180821-151959-root-SpatialNormalization.a0-9e488a0b-32af-4cc4-aa5f-33f844d645b7.txt 
Node: workflow_enumerator.anatMRIQCT1w.SpatialNormalization.SpatialNormalization
Working directory: /out/work/workflow_enumerator/anatMRIQCT1w/SpatialNormalization/_in_file_..data..sub-somelabel..ses-1..anat..sub-somelabel_ses-1_acq-main_T1w.nii.gz/SpatialNormalization

Node inputs:

compress_report = auto
explicit_masking = True
flavor = fast
float = False
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1
moving_image = /out/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-somelabel..ses-1..anat..sub-somelabel_ses-1_acq-main_T1w.nii.gz/inu_n4/sub-somelabel_ses-1_acq-main_T1w_conformed_corrected.nii.gz
moving_mask = /out/work/workflow_enumerator/anatMRIQCT1w/AFNISkullStripWorkflow/_in_file_..data..sub-somelabel..ses-1..anat..sub-somelabel_ses-1_acq-main_T1w.nii.gz/binarize/sub-somelabel_ses-1_acq-main_T1w_conformed_calc_thresh.nii.gz
num_threads = 1
orientation = RAS
out_report = report.svg
reference = T1
reference_image = <undefined>
reference_mask = /niworkflows_data/mni_icbm152_nlin_asym_09c/2mm_brainmask.nii.gz
settings = <undefined>
template = mni_icbm152_nlin_asym_09c
template_resolution = 2

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/mni.py", line 178, in _run_interface
    self._validate_results()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/mni.py", line 396, in _validate_results
    overlap_perc = float(overlap_voxel_count.sum()) / float(input_mask_data.sum()) * 100
ZeroDivisionError: float division by zero

```

**Comment by oesteban** [comment]
Could you provide us with this dataset to replicate, maybe privately?

**Comment by DavidEWarrenPhD** [comment]
After some additional inspection, it appears that the root cause may something about the DICOM-to-NIFTI conversion prior to MRIQC, although the failure is happening well into MRIQC processing.  I wonder whether you could point me to any free/open DICOM images that would allow me to attempt a replication of the issue?  Thanks.

**Comment by DavidEWarrenPhD** [comment]
Interesting, and it's very possible that this is the same issue.  I'll try clearing any AFNI extensions in the NIFTI headers tomorrow to confirm.

**Comment by oesteban** [comment]
That'd be wonderful. There is one more thing at play here, AFNI and ANTs implement the s/q-form headers of NIFTI in (almost opposite) different ways. In fMRIPrep we curate input data for that, but we don't in MRIQC and that could also be the issue. 

How to test? Using nibabel you can copy the s-form matrix and code over the q-form matrix and that should do.

**Comment by DavidEWarrenPhD** [comment]
Got it.  I'll report back when I've had a chance to try this out.

**Comment by jdkent** [comment]
To chime in and add support to the "extra information in the headers" hypothesis, I had a similar issue with `dimon` inserting additional information into the nifti header causing strange behavior (e.g. errors) working with `nibabel` and `mriqc`, removing that information allowed for the normal execution of those utilities.

If you want to continue using `dimon`, you can remove the "extra" information using `nifti_tool` as used in a script [here](https://github.com/HBClab/GE_dcm_to_nii/blob/280d1e76194fee20c85f5cbb53de575f3f920e58/GE_dcm_to_nii.sh#L886)

(although my personal vote is to use `dcm2niix` if possible)

**Comment by oesteban** [comment]
I'll go ahead and mark this duplicate #686. Please follow up there.

**Comment by oesteban** [comment]
BTW, thanks @DavidEWarrenPhD very much for this neat debugging work 👍
