### ISSUE TITLE
Empty approximate spatial normalization image in report

### ISSUE THREAD

**Issue by parekhpravesh** [poldracklab/mriqc#767]
Hello!

Its nice to be back to mriqc! Many new features! Thank you for your work.

I recently ran mriqc using the Docker version on Ubuntu for a large number of subjects. Everything ran fine but when I looked at subject specific reports (HTML files), I noticed that the "Approximate spatial normalization" part was blank i.e. the fixed and moving images were empty. Attached is an example. This happened for all the 358 subjects (I guess so; randomly checked quite a few reports) .

This is the command that I used:
`docker run -it --rm -v <fullpath_to_directory>:/data -v <full_path_to_directory>:/mounted_dir -w /scratch poldracklab/mriqc:latest /data /mounted_dir/out_dir --verbose-reports --n_procs 25 --mem_gb 28 --ants-nthreads 25 participant --participant_label 20170712101140004 -w /mounted_dir/work_dir`

Further, both the work_dir and out_dir were created with ownership to the root user, even though the directory is owned by the usual user and the command was issued from the same user. Could this be the cause...that mriqc failed to read the fixed and moving NIfTI files (they were created) due to ownership issues? This, of course, is a little contradictory since all other images were present in the report. Or could it be an issue with my docker configuration?

The report was generated properly if using the bare metal installation (though I had to downgrade FSL to get it to run (there was an issue about bet error when using FSL 6.0 but I can't seem to find it)).

As a side note, I randomly checked several of these 358. I think all subjects have the zero-filled frame error (#637). 

Thanks and Regards
Pravesh

![report](https://user-images.githubusercontent.com/8792123/51037450-4406ed00-15d6-11e9-9db4-e73306f06926.png)

**Comment by oesteban** [comment]
Hi @parekhpravesh, thanks very much for your feedback.

Before we go ahead debugging this, could you check whether this is still happening with the latest mriqc release? (which came out last week).

Thanks!

**Comment by parekhpravesh** [comment]
Hello @oesteban 
Apologies for the late reply. Indeed, it seems like the new release fixed this issue; I ran a few subjects just the other day and everything looks okay! Thank you!
