### ISSUE TITLE
fMRI QC on multi-echo data

### ISSUE THREAD

**Issue by mnarayan** [poldracklab/mriqc#773]
Hello, 

I have applied fMRI QC to each of 3 echoes from a multi-band multi-echo acquisition with 1 second TR. I find the estimated motion (DVARS, FD, 6 movement parameters) time-series looks different for each echo! I would have guessed these ought to be the identical but perhaps sub-TR differences between echoes are responsible for this. 

Is this surprising to you or something you would have expected? I'm just wondering if this could be a bug rather than a feature of the data. 

Thanks!

**Comment by oesteban** [comment]
Unfortunately, MRIQC is totally unaware of multiecho data. We should definitely update it for ME.

**Comment by mnarayan** [comment]
Thanks! As far as I can tell, there should be no reason for mriqc to do
anything wrong in analyzing multiple echoes. It worked perfectly from a
user standpoint. But I wanted to double check if you had any thoughts if
this inconsistency could be a bug.

Maybe this is a question for neurostars as well. Will post later.

**Comment by oesteban** [comment]
Sorry for the noise - this was opened when I removed the stale bot. Please dismiss notifications.
