### ISSUE TITLE
Bump up to pybids 0.9

### ISSUE THREAD

**Issue by effigies** [poldracklab/mriqc#776]
I would recommend skipping 0.7 altogether. This is related to [neurostars #3713](https://neurostars.org/t/no-module-named-bids-grabbids/3713), which is a custom installation running across a failure to import `bids.grabbids`. It's not clear how deep a rabbit hole moving up to 0.8 will end up being, so I'm starting an issue. If you don't have time, I can give it a shot this afternoon.

**Comment by alexlicohen** [comment]
The current requirements also make mriqc incompatible with fmriprep for bare-metal installation in the same environment...

**Comment by effigies** [comment]
Yes, that's definitely true. For the time being we would recommend using multiple [virtualenv](https://virtualenv.pypa.io/en/stable/) or conda environments.

**Comment by alexlicohen** [comment]
Testing it now, just rediscovering mriqc!

-Alex
