### ISSUE TITLE
run_id usage? TypeError: sequence item 0: expected str instance, int found

### ISSUE THREAD

**Issue by WillForan** [poldracklab/mriqc#789]
We are trying to run dockerized MRIQC on anat with BIDS like
```
 find /data2/MRI/PING/bids/sub-P0009/
/data2/MRI/PING/bids/sub-P0009/
/data2/MRI/PING/bids/sub-P0009/ses-01
/data2/MRI/PING/bids/sub-P0009/ses-01/anat
/data2/MRI/PING/bids/sub-P0009/ses-01/anat/sub-P0009_ses-01_T1w_run-01.json
/data2/MRI/PING/bids/sub-P0009/ses-01/anat/sub-P0009_ses-01_T1w_run-01.nii.gz
```

If we create
`/data2/MRI/PING/bids/sub-P0009/ses-01/anat/sub-P0009_ses-01_T1w.nii.gz`  instead and drop the use of `run_id`, we have no errors.  
> 2019-04-09 17:31:50,041 nipype.workflow:INFO Building anatomical MRIQC workflow, datasets list: ['sub-P0009/ses-01/anat/sub-P0009_ses-01_T1w.nii.gz']

But trying with `...T1w_run-01.nii.gz` fails.

We are using
```
docker run -it --rm -v /data2/MRI/PING/bids:/data:ro -v /data2/MRI/PING/MRIQC:/out poldracklab/mriqc:0.15.0 /data /out participant --participant_label P0009 --run-id 1
```

and getting the error

```
2019-04-09 17:31:10,028 mriqc:CRITICAL MRIQC did not find any target image file under the given BIDS folder (/data). Please check that the dataset is BIDS valid at http://bids-standard.github.io/bids-validator/ .
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc==0.15.0', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/bin/mriqc_run.py", line 234, in main
    bids_selectors += ['--%s %s' % (entity, ' '.join(values))]
TypeError: sequence item 0: expected str instance, int found
```

We also tried various combinations like `--run-id 01`, `--run-id "1"`, `--run-id "01"`

**Comment by oesteban** [comment]
Hi @WillForan, your dataset is not BIDS valid.

Can you try renaming the anatomicals?
```
/data2/MRI/PING/bids/sub-P0009/ses-01/anat/sub-P0009_ses-01_run-01_T1w.json
/data2/MRI/PING/bids/sub-P0009/ses-01/anat/sub-P0009_ses-01_run-01_T1w.nii.gz
```
BIDS requires the modality suffix to be the last entity of the name.

**Comment by WillForan** [comment]
That was it! Sorry for the noise
>  Building anatomical MRIQC workflow, datasets list: ['sub-P0009/ses-01/anat/sub-P0009_ses-01_run-01_T1w.nii.gz']

**Comment by WillForan** [comment]
in case anyone else ends up here, using `rename` (default on debian, `cpan install File::Rename` on redhat like distros)
```
rename -n 's/(sub-.*)(_T1w)(_run-\d+).(nii.gz|json)/$1$3$2.$4/' sub*/ses*/anat/sub-*T1w_run*.{nii.gz,json}
```
