### ISSUE TITLE
Possible discrepancy in group reports

### ISSUE THREAD

**Issue by dlevitas** [poldracklab/mriqc#794]
Hi,

I'm looking over my group report after running version ```0.15.0```, and there seems to be some differences between the html file and the .tsv file. 
![mriqc_group_bold_html](https://user-images.githubusercontent.com/25011343/59296895-007fe000-8c55-11e9-96e6-d292f8224fd4.png)

![mriqc_group_bold_tsv](https://user-images.githubusercontent.com/25011343/59296905-05dd2a80-8c55-11e9-9fa2-7758c9edb474.png)

In the html, the highest FD (mm) mean value is listed at approximately 0.12mm, while in the the tsv there are a few runs where the mean FD goes up to 0.22mm. These discrepancies also seem to appear in fd_num and fd_perc. I've made sure that all my data went through the individual MRIQC level before the group level, so I'm unsure if the values in the tsv don't perfectly correspond to what's in the html, or if it's something else.

Dan

**Comment by jdkent** [comment]
I forget how the range is determined, but if you were to hover your cursor over the values sitting at the highest point they _should_ display the correct value even though the range in the graph does not cover those values. I did a quick search through the issues to see if this was already covered, but I could not find another issue referencing this.

**Comment by dlevitas** [comment]
Thanks @jdkent, you're right, they get lumped in the with the other values at the high end.
