### ISSUE TITLE
Query regarding output of anat_qc_workflow.

### ISSUE THREAD

**Issue by kilimanjaro2** [poldracklab/mriqc#836]
Hi,

I am working on a custom modification of MRIQC for which I need to run the anatomical pipeline. For this, I follow the instructions mentioned at the beginning of the anat_qc_workflow function here:
https://github.com/poldracklab/mriqc/blob/master/mriqc/workflows/anatomical.py

The code executes without any errors. However, no files are present in the specified output directory once the execution is completed. Is there an option to get a verbose output? I don't know if I'm missing something here. Looking for some advice on how to proceed (I hope this is the right place). I've also attached a screenshot of the command I've run on my environment
![newAlternate](https://user-images.githubusercontent.com/16185077/77894443-ec17dd00-7292-11ea-85bc-831368d93273.png)
.

**Comment by oesteban** [comment]
That particular function only stages the anatomical workflow, which is a [Nipype](https://github.com/nipy/nipype) workflow.

To run the Nipype workflow once built, you should call `.run()` on the object `anat_qc_workflow()` returns.

To learn more about Nipype, please check out [its documentation](https://nipype.readthedocs.io/).

**Comment by kilimanjaro2** [comment]
Thanks for the quick response. Much appreciated.
