### ISSUE TITLE
Rebuild MRIQC RTD 

### ISSUE THREAD

**Issue by franklin-feingold** [poldracklab/mriqc#843]
The [current docs](https://mriqc.readthedocs.io/en/latest/) build mentions that one can run MRIQC directly on OpenNeuro. This function has since been deactivated

**Comment by ZviBaratz** [comment]
This will also resolve #830. In addition, it seems like `sphinx-apidoc` needs to be rerun as well (e.g. [`anat_qc_workflow`](https://mriqc.readthedocs.io/en/latest/_modules/mriqc/workflows/anatomical.html#anat_qc_workflow)'s reference is outdated.
