### ISSUE TITLE
no space left on device with singularity and MRIQC v0.15.2

### ISSUE THREAD

**Issue by DVSneuro** [poldracklab/mriqc#850]
Hi -- I'm running MRIQC v0.15.2 via singularity (command below), and I'm getting an `OSError: [Errno 28] No space left on device` error that I think must be linked to the container since I have I have plenty of space on the computer (see below). The full terminal output is attached, and I'm also attaching the log. Notably, I everything works find with v0.15.1. 

```
singularity run --cleanenv \
-B $dsroot/bids:/data \
-B $output:/out \
-B $scratch:/scratch \
/data/tools/mriqc-0.15.2.simg \
/data /out \
participant --participant_label $sub -w /scratch
```

For context, I made the singularity image with the command below:
`singularity build /data/tools/mriqc-0.15.2.simg docker://poldracklab/mriqc:0.15.2`

Also, here's my disk utlization:
```
(base) tug87422@cla18994 /data/projects/srndna-all $ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             63G     0   63G   0% /dev
tmpfs            13G  1.3G   12G  10% /run
/dev/nvme0n1p2  344G  174G  153G  54% /
tmpfs            63G  283M   63G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs            63G     0   63G   0% /sys/fs/cgroup
/dev/nvme0n1p1  511M  1.2M  510M   1% /boot/efi
/dev/md0         11T  7.9T  2.5T  77% /data
cgmfs           100K     0  100K   0% /run/cgmanager/fs
tmpfs            13G  164K   13G   1% /run/user/350685838
tmpfs            13G   72K   13G   1% /run/user/350612714
tmpfs            13G   96K   13G   1% /run/user/350682968
tmpfs            13G   40K   13G   1% /run/user/350601383
tmpfs            13G   36K   13G   1% /run/user/350530200
tmpfs            13G   40K   13G   1% /run/user/350726184
/dev/loop2       94M   94M     0 100% /snap/core/8935
/dev/loop3      143M  143M     0 100% /snap/slack/23
tmpfs            13G   60K   13G   1% /run/user/350644243
/dev/loop27      94M   94M     0 100% /snap/core/9066
tmpfs            13G  4.0K   13G   1% /run/user/108
tmpfs            13G   28K   13G   1% /run/user/350724727
/dev/loop6      140M  140M     0 100% /snap/slack/24
```

Any ideas? Perhaps as a related issue with singularity (even on successful runs), we've noticed that the bind points seem to persist after the job completes (i.e., it looks like multiple drives are mounted when viewing files), so maybe we're not using singularity as intended?

Thanks!
David

[crash-20200531-021945-tug87422-SpatialNormalization.a1-4478cdfb-95c2-446c-8027-74b76512bf12.txt](https://github.com/poldracklab/mriqc/files/4707998/crash-20200531-021945-tug87422-SpatialNormalization.a1-4478cdfb-95c2-446c-8027-74b76512bf12.txt)

[mriqc_terminaloutput.txt](https://github.com/poldracklab/mriqc/files/4708000/mriqc_terminaloutput.txt)

**Comment by cni-md** [comment]
Is there any solution for this problem? It is still present with 0.16.1 and the last version running with singularity is 0.15.1.

I was happy to see a singularity container 0.16.1 in the neurodocker, but this version is also not working.

**Comment by DVSneuro** [comment]
I'm having the same issue with 0.16.1, but I found this helpful post on NeuroStars:
https://neurostars.org/t/mriqc-no-space-left-on-device-error/16187/1

I just got mine to work with the code block below:
```
# no space left on device error for v0.15.2 and higher
# https://neurostars.org/t/mriqc-no-space-left-on-device-error/16187/1
# https://github.com/poldracklab/mriqc/issues/850
TEMPLATEFLOW_DIR=/data/tools/templateflow
export SINGULARITYENV_TEMPLATEFLOW_HOME=/opt/templateflow
singularity run --cleanenv \
-B ${TEMPLATEFLOW_DIR}:/opt/templateflow \
-B $dsroot/bids:/data \
-B $dsroot/derivatives/mriqc:/out \
-B $scratch:/scratch \
/data/tools/mriqc-0.16.1.simg \
/data /out \
participant --participant_label $sub -w /scratch
```

I am not sure if this really closes the issue, but I defer to @oesteban

**Comment by oesteban** [comment]
Hi, yes, it is very likely that you were using all `/tmp` before you bound a writeable folder into `/scratch` and then pointed at it with `-w /scratch`.

For further questions about singularity, please check this piece of documentation - https://www.nipreps.org/apps/singularity/

Thanks for your understanding given the super-slow response.
