### ISSUE TITLE
How to use multithreading with --nproc / ERROR: type object 'nipype' has no attribute 'omp_nthread'

### ISSUE THREAD

**Issue by dfsp-spirit** [poldracklab/mriqc#851]
I am trying to use several cores (the machine has 48) for running mriqc, using the latest Docker container (v0.15.2), but I am getting the following error:

    docker run -it --rm -v /home/myuser/data/:/data:ro -v /home/myuser/mriqc_aims:/out poldracklab/mriqc:latest /data /out participant --no-sub --nproc 40
    Traceback (most recent call last):
    File "/usr/local/miniconda/bin/mriqc", line 10, in <module>
    sys.exit(main())
    File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 15, in main
    parse_args()
    File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/parser.py", line 395, in parse_args
    config.nipype.omp_nthread,
    AttributeError: type object 'nipype' has no attribute 'omp_nthread'

If I run the same command, but leave out the `--nproc 40` part, it works fine (but takes ages, I have >700 subjects and it's been running all day and has not finished yet).

What should I do to get multithreading to work?

**Comment by schlinde** [comment]
I have the same problem running the latest version. My workaround is to go back to version 0.10.3

**Comment by effigies** [comment]
This should be fixed in #846. Please use version 0.15.3.

**Comment by dfsp-spirit** [comment]
Thanks for the fix!
