### ISSUE TITLE
webapi via curl SSL error 

### ISSUE THREAD

**Issue by wiheto** [poldracklab/mriqc#858]
So accessing the web api for MRIQC has changed its functionality recently. It used to be possible to run, for example:

`curl -X GET "https://mriqc.nimh.nih.gov/api/v1/rating" -H "accept: application/json"`

But we now get a SSL error: 

> curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: https://curl.haxx.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above.

The fix is possible by adding a `--insecure` flag, but it would obviously be optimal if this could be fixed? Seems like the SSL certificate may need renewing(?)

**Comment by oesteban** [comment]
We have just fixed some issues on the web API end, but, if this persists, can I page @rwblair here?

**Comment by wiheto** [comment]
Seems to be working. If the issue pops up again I will let you know. Thanks! :)
