### ISSUE TITLE
Install MRIQC with Singularity containers on HPC

### ISSUE THREAD

**Issue by anlijuncn** [poldracklab/mriqc#860]
Hi 

Do you know how to install MRIQC with Singularity containers on HPC? 

I could not find instructions on https://mriqc.readthedocs.io/en/stable/running.html#singularity-containers

**Comment by julfou81** [comment]
`singularity build <path to your images>/mriqc-<version>.simg docker://poldracklab/mriqc:<version>`

for example:

`singularity build my_images/mriqc-0.15.1.simg docker://poldracklab/mriqc:0.15.1`

**Comment by effigies** [comment]
Seems to have been answered. Please reopen if you need further help.
