### ISSUE TITLE
Docker (linux rootless) 

### ISSUE THREAD

**Issue by treanus** [poldracklab/mriqc#878]
Hi,
 having the error below on an Linux Mint (ubuntu 20.04) system with rootless docker (https://docs.docker.com/engine/security/rootless/).

The rootless docker works fine with fmriprep.

Any ideas how to solve this?

Thx in advance, 
Stefan.

```
docker run -it --rm  -v /DATA/test_sarah/BIDS:/data:ro -v /DATA/test_sarah/mriqc:/out  poldracklab/mriqc:latest  --participant_label 001  /data /out participant
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/DATA/test_sarah/BIDS\\\" to rootfs \\\"/home/stefan/.local/share/docker/overlay2/d6a0808f7a4fa449d6b895b96825f6e95bfae47ea86b4579c866c4fb1508daa5/merged\\\" at \\\"/home/stefan/.local/share/docker/overlay2/d6a0808f7a4fa449d6b895b96825f6e95bfae47ea86b4579c866c4fb1508daa5/merged/data\\\" caused \\\"operation not permitted\\\"\"": unknown.
```

**Comment by oesteban** [comment]
Have you tried to mount the same path `/DATA/test_sarah/BIDS` in readonly mode, but with fMRIPrep's docker image?

I suspect this folder might be some special network filesystem. Alternatively, it seems docker is trying to use `rootfs` for this binding (which I don't really know whether is a problem or not).

**Comment by treanus** [comment]
Removing the read only mount dd the job! Thank you!
Issue can be closed.
