### ISSUE TITLE
mriqc_wf.funcMRIQC.ComputeIQMs.metadata

### ISSUE THREAD

**Issue by costantinoai** [poldracklab/mriqc#879]
Hi,

I am using mriqc with docker on a BIDS dataset. when i run 

docker run -it --rm -v D:\Andrea\fov\scratch:/scratch -v D:\Andrea\fov\BIDS:/data:ro -v D:\Andrea\fov\BIDS\derivatives\mriqc:/out poldracklab/mriqc:latest /data /out participant -w /scratch --write-graph --participant_label sub-02 --verbose --no-sub

I get this error:

> 201218-00:11:25,936 nipype.workflow WARNING:
>          [Node] Error on "mriqc_wf.funcMRIQC.ComputeIQMs.metadata" (/scratch/mriqc_wf/funcMRIQC/ComputeIQMs/_in_file_..data..sub-02..func..sub-02_task-loc_run-1_bold.nii.gz/metadata)
> 201218-00:11:26,27 nipype.workflow ERROR:
>          Node metadata.a5 failed to run on host b326747ca479.
> 201218-00:11:26,28 nipype.workflow ERROR:
>          Saving crash info to /out/logs/crash-20201218-001126-root-metadata.a5-fd26f8a3-d96c-4a54-b1c6-98a3e7dc6ab6.txt
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
>     self.procs[jobid].run(updatehash=updatehash)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 764, in _run_command
>     dirs2keep=dirs2keep,
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1482, in clean_working_directory
>     output_files.extend(walk_outputs(outputdict[output]))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1452, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1455, in walk_outputs
>     if os.path.islink(object) or os.path.isfile(object):
>   File "/usr/local/miniconda/lib/python3.7/posixpath.py", line 171, in islink
>     st = os.lstat(path)
> ValueError: embedded null byte
> 
> 
> When creating this crashfile, the results file corresponding
> to the node could not be found.
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
>     self.procs[jobid].run(updatehash=updatehash)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 764, in _run_command
>     dirs2keep=dirs2keep,
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1482, in clean_working_directory
>     output_files.extend(walk_outputs(outputdict[output]))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1452, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1455, in walk_outputs
>     if os.path.islink(object) or os.path.isfile(object):
>   File "/usr/local/miniconda/lib/python3.7/posixpath.py", line 171, in islink
>     st = os.lstat(path)
> ValueError: embedded null byte
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/miniconda/bin/mriqc", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/miniconda/lib/python3.7/site-packages/mriqc/cli/run.py", line 69, in main
>     mriqc_wf.run(**config.nipype.get_plugin())
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 632, in run
>     runner.run(execgraph, updatehash=updatehash, config=self.config)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 184, in run
>     self._send_procs_to_workers(updatehash=updatehash, graph=graph)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 348, in _send_procs_to_workers
>     jobid, graph, result={"result": None, "traceback": traceback}
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
>     raise RuntimeError("".join(result["traceback"]))
> RuntimeError: Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
>     self.procs[jobid].run(updatehash=updatehash)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 764, in _run_command
>     dirs2keep=dirs2keep,
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1482, in clean_working_directory
>     output_files.extend(walk_outputs(outputdict[output]))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1452, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1455, in walk_outputs
>     if os.path.islink(object) or os.path.isfile(object):
>   File "/usr/local/miniconda/lib/python3.7/posixpath.py", line 171, in islink
>     st = os.lstat(path)
> ValueError: embedded null byte

crash file:

> Node: mriqc_wf.funcMRIQC.ComputeIQMs.metadata
> Working directory: /scratch/mriqc_wf/funcMRIQC/ComputeIQMs/_in_file_..data..sub-02..func..sub-02_task-loc_run-1_bold.nii.gz/metadata
> 
> Node inputs:
> 
> bids_dir = None
> bids_validate = True
> in_file = /data/sub-02/func/sub-02_task-loc_run-1_bold.nii.gz
> 
> Traceback (most recent call last):
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
>     self.procs[jobid].run(updatehash=updatehash)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 764, in _run_command
>     dirs2keep=dirs2keep,
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1482, in clean_working_directory
>     output_files.extend(walk_outputs(outputdict[output]))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1448, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1452, in walk_outputs
>     out.extend(walk_outputs(val))
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 1455, in walk_outputs
>     if os.path.islink(object) or os.path.isfile(object):
>   File "/usr/local/miniconda/lib/python3.7/posixpath.py", line 171, in islink
>     st = os.lstat(path)
> ValueError: embedded null byte
> 
> 
> When creating this crashfile, the results file corresponding
> to the node could not be found.

The same error comes up if I select another participant, so it's unlikely to be related to the file itself.

Any idea what is going on?

**Comment by costantinoai** [comment]
update: I tried to run on some other participants, and MRIQC runs just fine. What could be the problem? the sidecar JSON files for the nii.gz that are causing the problem look fine.

Thanks

**Comment by oesteban** [comment]
The following message

```
ValueError: embedded null byte
```

seems to indicate that there's some problem with some specific JSON files, with the encoding or the presence of unsupported characters. Does the validator pass on these files?

**Comment by costantinoai** [comment]
I get some errors:
>  .CogAtlasID should match format "uri", but my understanding is that this is not a major issue (is it?).
and some warnings related to missing files/subjects and unexpected files (I saved a non-BIDS logfile in the folder).

**Comment by oesteban** [comment]
MRIQC expects a valid BIDS dataset, fixing those issues will possibly make it run properly.

**Comment by oesteban** [comment]
(also, that opening, saving and closing those JSON files may fix the problematic characters, if your editor is smart enough)

**Comment by costantinoai** [comment]
Great, thanks. I'll try that!

**Comment by costantinoai** [comment]
So, I tried fixing the errors on the BIDS dataset and opening, saving and closing the JSON file but I still get the same error. I don't know how smart my editor is (I used Notepad++) though. 

What encoding is MRIQC expecting? and what are the invalid characters?

Thanks

**Comment by costantinoai** [comment]
I compared some JSON files responsible of this error with other JSONs that didn't raise any problem, and it turns out the problematic field is 'DataSetTrailingPadding' inside `time`, `samples`. Following [this issue](https://github.com/nipy/heudiconv/issues/303#issue-405842809) it looks like heudiconv copies this field from the DICOM header, but the field is not really relevant for further steps and it is safe to remove. 

If anyone else incur in the same issue, this is the code I used to solve the issue on these files:

```
import json
import glob
from shutil import copyfile
import os, stat

## UPDATE COGATLASID in BIDS sub folders
root_path = r"D:\Andrea\fov\BIDS\*\*\*run-?*_bold.json"
backup_dir = r"D:\Andrea\fov\misc\json_backup"
  
for name in glob.glob(root_path):
    copyfile(name, os.path.join(backup_dir, os.path.split(name)[1]))  # backup the original file
    os.chmod(name, stat.S_IWRITE)
    with open(name, 'r') as a:
        j = json.load(a)
        if 'DataSetTrailingPadding' in j['time']['samples']:
            del j['time']['samples']['DataSetTrailingPadding']
            print(name + ' has been fixed')
    with open(name, 'w', encoding='utf-8') as a:
        json.dump(j, a, ensure_ascii=False, indent=4)

```

**Comment by oesteban** [comment]
Thanks for reporting back on the solution. Glad you got this fixed.

@mgxd do you think we should upstream this problem to HeudiConv?
