### ISSUE TITLE
Relative imports to absolute imports

### ISSUE THREAD

**Issue by ZviBaratz** [poldracklab/mriqc#903]
I propose changing the default import style to absolute imports. I believe it is considered safer and more readable.

**Comment by oesteban** [comment]
> I believe it is considered safer

who says so? I have the opposite feeling... Especially developing it is easier to test/debug the wrong code if you are a newbie (and indeed one of the recommendations migrating from python 2.5 to +2.7 was to use relative imports)

> and more readable

We are not talking about the walrus operator - let's say both are equally readable :D

**Comment by oesteban** [comment]
Chris just replied within the PR - https://github.com/poldracklab/mriqc/pull/901#discussion_r583644356. Let's follow up there.
