### ISSUE TITLE
changing parameters for motion correction

### ISSUE THREAD

**Issue by leehweeling** [poldracklab/mriqc#911]
Hi all,

I'm new to the MRIQC toolbox. From my understanding it uses AFNI 3dvolreg for motion correction. The default setting is to use the mean image as the reference image for motion correction. How can I change this to use the first image as the reference image for motion correction? Also, other than plotting DVARS and FD, is it possible to define the plots to show the 6 motion parameters?

Thanks.

Cheers,
Hweeling

**Comment by oesteban** [comment]
I don't remember if that can be done - but you shouldn't do it.

MRIQC is not supposed to process your data in any ways. Changing the reference will make previously calculated FD estimates very different and therefore, we would need a very good reason to allow that.

Please check our paper - https://doi.org/10.1038/s41596-020-0327-3 (there's a preprint on biorxiv if you can't go past the paywall) to understand the rationale behind my response.

If you want standardized preprocessing, please use fMRIPrep. fMRIPrep will generate a BIDS-Derivatives compatible `_confounds.tsv` file where you'll find the 6 motion parameters (amongst other confounding signals).
